type literal = V of int | NV of int;;
type clause = literal list;;
type cnf = clause list;;

type proposition =
  | Var of int
  | Not of proposition
  | And of proposition * proposition
  | Or of proposition * proposition

let rec nnf prop =
  match prop with
  | Var _ -> prop
  | Not (Var _ as v) -> Not v
  | Not (Not p) -> nnf p
  | Not (And (p, q)) -> Or (nnf (Not p), nnf (Not q))
  | Not (Or (p, q)) -> And (nnf (Not p), nnf (Not q))
  | And (p, q) -> And (nnf p, nnf q)
  | Or (p, q) -> Or (nnf p, nnf q)

let rec distribute_or p1 p2 =
  match (p1, p2) with
  | (And (a, b), x) ->
      And (distribute_or a x, distribute_or b x)
  | (x, And (a, b)) ->
      And (distribute_or x a, distribute_or x b)
  | _ -> Or (p1, p2)

let rec to_cnf prop =
  match prop with
  | And (p, q) -> And (to_cnf p, to_cnf q)
  | Or (p, q) ->
      let cp = to_cnf p in
      let cq = to_cnf q in
      distribute_or cp cq
  | _ -> prop

let rec prop_to_cnf prop =
  prop
  |> nnf
  |> to_cnf

  let rec literal_of_prop p =
  match p with
  | Var n -> V n
  | Not (Var n) -> NV n
  | _ -> failwith "Invalid literal in clause"

let rec prop_to_cnf_data prop =
  match prop with
  | And (p, q) ->
      (prop_to_cnf_data p) @ (prop_to_cnf_data q)
  | _ ->
      (* a clause is a disjunction of literals *)
      let rec gather_literals p lits =
        match p with
        | Or (p1, p2) -> gather_literals p1 (gather_literals p2 lits)
        | _ ->
            let lit = literal_of_prop p in
            lit :: lits
      in
      [gather_literals prop []]

let proposition_to_cnf p =
  p |> prop_to_cnf |> prop_to_cnf_data

let litt_of_name_and_bool x b =
  if b then V x else NV x;;

let printclause c=
  Printf.printf "[";
  let rec aux = function
      [] ->  Printf.printf "]";
    | l::q -> match l with
      | NV x ->  Printf.printf "NV %d; " x; aux q;
      | V x -> Printf.printf "V %d; " x; aux q;
  in aux c
;;

let printprop p =  Printf.printf "prop = [";
  let rec aux = function
      [] ->  Printf.printf "]\n";
    | c::q -> printclause c; aux q;
  in aux p;;

let delete_lit (c:clause) (x:int) (b:bool) =
  List.filter
    ((<>) @@ litt_of_name_and_bool x (not b))
    c;;

let rec subst (f:cnf) (x:int) (b:bool) : cnf option  =
  match f with
    [] -> Some []
  | c::q -> let q' =  subst q x b in
            match q' with
            | None -> None
            | Some q2 -> let c = delete_lit c x b in
                         if c = [] then None else
                           if List.mem (litt_of_name_and_bool x b) c
                           then Some q2
                           else Some (c::q2);;

let get_var (f:cnf) : int = match f with 
  | (V x::_)::_ | (NV x::_)::_ -> x
  | _ -> failwith "pas de variable";;

let rec quine f = match f with
  | [] -> true
  | _ -> let x = get_var f in
    (*totest : substitution partielle*)
    let rec aux f totest =   match totest with
      | [] -> false (*on a testé x<-T et x<-F sans succès*)
      | b::q -> let sf = subst f x b (*x<-b*)
        in match sf with
        | Some f2 ->
           if quine f2
           then true (*un choix de substitution donne true*)
           else aux f q (*x<-b marche pas,on essaye le suivant*)
        | None -> aux f q
    in aux f [true;false];;

let sat (f:proposition) : bool = quine @@ proposition_to_cnf f;;

let formulas = [|(And(Var 0,Var 0));
(And(Not(Var 0),Or(Not(Var 1),Not(Var 1))));
(And(Not(Var 0),Or(Var 1,And(Var 0,Var 1))));
(And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Not(Var 1),Not(Var 1))))));
(And(Var 2,Or(Not(Var 1),And(Var 0,Or(Var 2,And(Var 2,Var 1))))));
(And(Not(Var 0),Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,Var 0)))))));
(And(Not(Var 0),Or(Not(Var 2),And(Var 1,Or(Not(Var 2),And(Not(Var 3),Or(Var 2,And(Not(Var 1),Not(Var 2)))))))));
(And(Var 1,Or(Not(Var 4),And(Var 2,Or(Var 1,And(Var 0,Or(Not(Var 4),And(Var 2,Or(Not(Var 0),Not(Var 3))))))))));
(And(Not(Var 0),Or(Not(Var 0),And(Var 1,Or(Var 0,And(Var 2,Or(Not(Var 2),And(Not(Var 0),Or(Var 1,And(Not(Var 1),Not(Var 1)))))))))));
(And(Not(Var 2),Or(Not(Var 2),And(Var 1,Or(Var 1,And(Not(Var 2),Or(Not(Var 0),And(Var 2,Or(Not(Var 1),And(Var 1,Or(Var 1,Var 1)))))))))));
(And(Not(Var 4),Or(Var 1,And(Not(Var 3),Or(Not(Var 1),And(Var 3,Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 3),And(Var 2,Or(Var 1,And(Not(Var 0),Not(Var 3)))))))))))));
(And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),Not(Var 0))))))))))))));
(And(Not(Var 5),Or(Var 3,And(Not(Var 2),Or(Not(Var 0),And(Not(Var 3),Or(Var 1,And(Not(Var 5),Or(Not(Var 1),And(Not(Var 5),Or(Var 6,And(Not(Var 3),Or(Var 2,And(Not(Var 3),Not(Var 3)))))))))))))));
(And(Not(Var 1),Or(Var 2,And(Not(Var 1),Or(Var 2,And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Var 0,And(Not(Var 2),Or(Var 1,And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Var 1,Var 0)))))))))))))));
(And(Var 1,Or(Var 1,And(Not(Var 3),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 3),Or(Var 3,And(Var 2,Or(Var 1,And(Var 3,Or(Var 0,And(Var 2,Or(Not(Var 4),And(Var 4,Var 4))))))))))))))));
(And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),Not(Var 0))))))))))))))))));
(And(Var 2,Or(Var 2,And(Not(Var 2),Or(Var 3,And(Var 3,Or(Var 0,And(Var 0,Or(Var 2,And(Var 2,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 2),And(Not(Var 0),Or(Var 1,And(Var 1,Var 3))))))))))))))))));
(And(Var 1,Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Var 1,Or(Var 0,And(Var 1,Or(Var 1,And(Var 0,Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 1,Or(Var 1,And(Var 0,Or(Var 0,Var 1)))))))))))))))))));
(And(Var 3,Or(Not(Var 0),And(Var 4,Or(Var 0,And(Var 9,Or(Var 5,And(Var 5,Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 1),And(Not(Var 6),Or(Not(Var 2),And(Var 6,Or(Var 0,And(Var 2,Or(Not(Var 3),And(Var 9,Or(Var 1,And(Not(Var 1),Not(Var 0)))))))))))))))))))));
(And(Not(Var 7),Or(Var 7,And(Var 2,Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 6),And(Not(Var 2),Or(Not(Var 6),And(Var 1,Or(Var 2,And(Not(Var 2),Or(Var 7,And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 5),And(Not(Var 1),Or(Not(Var 6),And(Var 3,Or(Var 3,Var 6)))))))))))))))))))));
(And(Var 8,Or(Not(Var 2),And(Not(Var 1),Or(Var 2,And(Not(Var 4),Or(Not(Var 3),And(Not(Var 2),Or(Var 7,And(Not(Var 6),Or(Var 4,And(Not(Var 4),Or(Var 6,And(Not(Var 6),Or(Var 6,And(Not(Var 0),Or(Var 2,And(Var 10,Or(Var 9,And(Not(Var 1),Or(Var 5,And(Var 3,Var 5))))))))))))))))))))));
(And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),Not(Var 0))))))))))))))))))))))));
(And(Var 6,Or(Not(Var 2),And(Var 7,Or(Var 2,And(Not(Var 3),Or(Var 2,And(Not(Var 4),Or(Not(Var 7),And(Var 4,Or(Not(Var 7),And(Var 0,Or(Not(Var 7),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 5),Or(Var 0,And(Var 2,Or(Not(Var 4),And(Var 1,Or(Var 6,And(Var 6,Or(Var 7,And(Var 2,Var 1))))))))))))))))))))))));
(And(Not(Var 5),Or(Var 5,And(Var 5,Or(Not(Var 8),And(Not(Var 8),Or(Not(Var 6),And(Var 4,Or(Not(Var 1),And(Not(Var 5),Or(Var 8,And(Var 7,Or(Not(Var 11),And(Not(Var 11),Or(Var 2,And(Not(Var 1),Or(Var 0,And(Not(Var 2),Or(Not(Var 5),And(Not(Var 5),Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 10),And(Var 5,Or(Not(Var 7),Not(Var 11))))))))))))))))))))))))));
(And(Not(Var 4),Or(Not(Var 1),And(Not(Var 4),Or(Var 4,And(Var 2,Or(Not(Var 3),And(Var 2,Or(Not(Var 1),And(Not(Var 2),Or(Var 2,And(Var 2,Or(Var 4,And(Var 0,Or(Not(Var 2),And(Var 1,Or(Var 0,And(Not(Var 2),Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 3),And(Var 0,Or(Not(Var 0),And(Var 1,Or(Not(Var 2),And(Var 0,Var 4))))))))))))))))))))))))));
(And(Var 3,Or(Var 1,And(Var 2,Or(Not(Var 3),And(Var 3,Or(Not(Var 0),And(Not(Var 0),Or(Var 1,And(Var 2,Or(Not(Var 4),And(Not(Var 4),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 3),Or(Not(Var 5),And(Not(Var 3),Or(Var 4,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 2,And(Var 3,Or(Not(Var 1),And(Var 1,Or(Not(Var 2),Not(Var 4))))))))))))))))))))))))))));
(And(Var 7,Or(Not(Var 2),And(Var 5,Or(Not(Var 9),And(Not(Var 3),Or(Not(Var 12),And(Not(Var 3),Or(Not(Var 0),And(Not(Var 12),Or(Var 3,And(Var 3,Or(Not(Var 7),And(Var 6,Or(Var 5,And(Var 10,Or(Var 2,And(Not(Var 6),Or(Not(Var 5),And(Var 10,Or(Not(Var 5),And(Var 4,Or(Var 2,And(Not(Var 12),Or(Not(Var 10),And(Not(Var 4),Or(Not(Var 8),And(Var 6,Var 1))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 1,And(Var 1,Or(Not(Var 1),And(Var 1,Or(Var 1,And(Var 1,Or(Var 0,And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 1,Or(Var 0,And(Var 1,Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 0),Or(Not(Var 1),Not(Var 1))))))))))))))))))))))))))))));
(And(Var 6,Or(Not(Var 3),And(Not(Var 5),Or(Not(Var 10),And(Not(Var 2),Or(Var 3,And(Not(Var 4),Or(Var 4,And(Not(Var 10),Or(Var 8,And(Var 3,Or(Not(Var 0),And(Not(Var 0),Or(Var 1,And(Var 2,Or(Not(Var 9),And(Var 11,Or(Var 4,And(Not(Var 0),Or(Var 2,And(Var 2,Or(Not(Var 8),And(Not(Var 11),Or(Not(Var 3),And(Not(Var 7),Or(Var 12,And(Var 4,Or(Var 3,And(Not(Var 2),Not(Var 1)))))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 11,And(Var 6,Or(Not(Var 6),And(Var 12,Or(Not(Var 9),And(Not(Var 3),Or(Not(Var 11),And(Not(Var 8),Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 5,And(Not(Var 8),Or(Not(Var 7),And(Not(Var 10),Or(Var 11,And(Not(Var 11),Or(Not(Var 0),And(Not(Var 5),Or(Not(Var 8),And(Var 0,Or(Var 10,And(Var 8,Or(Not(Var 12),And(Var 6,Or(Var 10,And(Var 5,Or(Var 4,Var 10)))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 1,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 1),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 1,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Var 1,And(Var 0,Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Var 1,Var 0))))))))))))))))))))))))))))))));
(And(Not(Var 6),Or(Not(Var 3),And(Var 0,Or(Var 0,And(Not(Var 3),Or(Not(Var 2),And(Not(Var 4),Or(Var 2,And(Var 1,Or(Var 6,And(Var 3,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Var 0,And(Var 6,Or(Not(Var 4),And(Var 0,Or(Not(Var 3),And(Var 5,Or(Var 2,And(Var 0,Or(Not(Var 6),And(Var 1,Or(Not(Var 3),And(Not(Var 1),Or(Var 6,And(Var 6,Or(Not(Var 6),And(Not(Var 2),Or(Not(Var 4),Not(Var 2))))))))))))))))))))))))))))))))));
(And(Not(Var 4),Or(Var 2,And(Var 6,Or(Var 3,And(Var 8,Or(Not(Var 8),And(Var 10,Or(Var 6,And(Var 8,Or(Not(Var 3),And(Not(Var 10),Or(Var 9,And(Not(Var 5),Or(Not(Var 8),And(Var 6,Or(Var 4,And(Not(Var 5),Or(Var 8,And(Not(Var 11),Or(Not(Var 10),And(Not(Var 0),Or(Var 5,And(Var 2,Or(Var 4,And(Var 2,Or(Not(Var 9),And(Not(Var 5),Or(Not(Var 7),And(Not(Var 11),Or(Not(Var 5),And(Var 9,Or(Var 11,And(Not(Var 7),Not(Var 9)))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 1,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Not(Var 1),Or(Var 1,And(Var 0,Or(Var 1,And(Not(Var 0),Or(Var 0,And(Var 1,Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Var 0,And(Not(Var 1),Or(Var 1,And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 0,And(Not(Var 0),Or(Not(Var 1),Not(Var 0))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 6,And(Not(Var 3),Or(Not(Var 3),And(Var 2,Or(Var 0,And(Not(Var 4),Or(Var 6,And(Var 5,Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 1),And(Var 1,Or(Var 2,And(Not(Var 7),Or(Var 6,And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 6),Or(Not(Var 5),And(Var 1,Or(Var 1,And(Var 2,Or(Not(Var 2),And(Var 6,Or(Not(Var 5),And(Var 2,Or(Not(Var 6),And(Var 4,Or(Var 0,And(Var 5,Or(Var 3,And(Var 6,Var 2))))))))))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 11,And(Not(Var 7),Or(Not(Var 8),And(Not(Var 1),Or(Var 8,And(Not(Var 10),Or(Not(Var 3),And(Var 2,Or(Var 3,And(Var 3,Or(Var 6,And(Not(Var 10),Or(Var 11,And(Not(Var 6),Or(Var 2,And(Not(Var 1),Or(Not(Var 10),And(Not(Var 3),Or(Var 9,And(Var 1,Or(Not(Var 3),And(Var 8,Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 11),And(Var 3,Or(Var 8,And(Not(Var 7),Or(Not(Var 2),And(Not(Var 7),Or(Var 5,And(Not(Var 6),Or(Not(Var 7),And(Var 6,Or(Var 0,Var 1)))))))))))))))))))))))))))))))))))));
(And(Var 10,Or(Var 15,And(Var 0,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 1),And(Var 11,Or(Not(Var 11),And(Var 2,Or(Not(Var 1),And(Var 12,Or(Not(Var 1),And(Var 12,Or(Not(Var 6),And(Not(Var 1),Or(Var 13,And(Var 6,Or(Not(Var 9),And(Var 4,Or(Not(Var 13),And(Not(Var 9),Or(Not(Var 3),And(Var 7,Or(Not(Var 5),And(Not(Var 13),Or(Not(Var 5),And(Not(Var 1),Or(Not(Var 4),And(Var 3,Or(Var 8,And(Not(Var 8),Or(Not(Var 7),And(Not(Var 11),Or(Not(Var 7),And(Not(Var 10),Or(Not(Var 13),And(Var 0,Var 3))))))))))))))))))))))))))))))))))))));
(And(Var 4,Or(Not(Var 3),And(Not(Var 2),Or(Var 12,And(Var 7,Or(Var 12,And(Not(Var 5),Or(Var 3,And(Var 0,Or(Var 2,And(Var 4,Or(Not(Var 11),And(Var 10,Or(Var 3,And(Not(Var 1),Or(Var 10,And(Not(Var 7),Or(Var 4,And(Var 7,Or(Not(Var 6),And(Var 9,Or(Not(Var 3),And(Not(Var 12),Or(Not(Var 8),And(Not(Var 9),Or(Not(Var 5),And(Var 1,Or(Var 6,And(Not(Var 2),Or(Not(Var 12),And(Var 4,Or(Not(Var 11),And(Not(Var 11),Or(Not(Var 0),And(Var 5,Or(Var 6,And(Not(Var 8),Or(Var 12,Var 9)))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 2),And(Var 7,Or(Var 6,And(Not(Var 5),Or(Not(Var 0),And(Not(Var 1),Or(Var 4,And(Var 5,Or(Var 1,And(Var 3,Or(Var 0,And(Not(Var 7),Or(Not(Var 3),And(Not(Var 5),Or(Not(Var 4),And(Var 3,Or(Not(Var 3),And(Var 7,Or(Not(Var 5),And(Not(Var 0),Or(Not(Var 6),And(Not(Var 0),Or(Var 1,And(Var 4,Or(Not(Var 3),And(Not(Var 2),Or(Var 2,And(Var 7,Or(Var 4,And(Var 4,Or(Var 6,And(Not(Var 1),Or(Var 1,And(Not(Var 5),Or(Not(Var 7),And(Var 4,Or(Var 2,And(Not(Var 7),Not(Var 1)))))))))))))))))))))))))))))))))))))))));
(And(Var 4,Or(Var 4,And(Var 9,Or(Var 6,And(Var 10,Or(Not(Var 7),And(Not(Var 3),Or(Var 3,And(Var 12,Or(Not(Var 4),And(Var 1,Or(Not(Var 1),And(Not(Var 14),Or(Not(Var 3),And(Not(Var 0),Or(Var 11,And(Not(Var 9),Or(Var 12,And(Not(Var 1),Or(Not(Var 12),And(Var 12,Or(Not(Var 11),And(Not(Var 11),Or(Not(Var 10),And(Var 5,Or(Var 1,And(Var 7,Or(Var 10,And(Var 4,Or(Var 1,And(Var 12,Or(Var 4,And(Not(Var 12),Or(Var 7,And(Var 7,Or(Not(Var 3),And(Var 13,Or(Not(Var 4),And(Not(Var 3),Or(Var 0,Var 11)))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 17),Or(Not(Var 7),And(Var 14,Or(Var 5,And(Var 5,Or(Not(Var 11),And(Not(Var 4),Or(Not(Var 5),And(Not(Var 18),Or(Var 3,And(Var 3,Or(Not(Var 11),And(Var 5,Or(Var 9,And(Var 16,Or(Var 9,And(Not(Var 2),Or(Var 7,And(Var 3,Or(Var 16,And(Var 7,Or(Var 14,And(Not(Var 7),Or(Var 17,And(Var 10,Or(Not(Var 9),And(Var 1,Or(Var 12,And(Var 1,Or(Var 8,And(Var 3,Or(Var 11,And(Var 6,Or(Var 11,And(Var 11,Or(Var 17,And(Var 17,Or(Not(Var 18),And(Not(Var 14),Or(Var 7,And(Not(Var 8),Not(Var 1)))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Not(Var 1),And(Var 8,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 3),And(Var 7,Or(Var 5,And(Var 9,Or(Var 1,And(Var 6,Or(Var 15,And(Not(Var 6),Or(Var 3,And(Not(Var 12),Or(Not(Var 15),And(Var 8,Or(Var 3,And(Var 3,Or(Not(Var 14),And(Var 11,Or(Var 14,And(Var 3,Or(Not(Var 6),And(Not(Var 5),Or(Var 2,And(Not(Var 10),Or(Var 6,And(Not(Var 13),Or(Not(Var 10),And(Var 3,Or(Var 9,And(Not(Var 1),Or(Var 14,And(Not(Var 5),Or(Var 15,And(Var 4,Or(Not(Var 2),And(Not(Var 7),Or(Not(Var 5),And(Not(Var 13),Or(Not(Var 13),Not(Var 10))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 3,And(Var 10,Or(Var 4,And(Var 6,Or(Not(Var 0),And(Var 9,Or(Not(Var 5),And(Var 10,Or(Var 12,And(Not(Var 9),Or(Var 7,And(Not(Var 5),Or(Var 7,And(Var 9,Or(Var 0,And(Not(Var 2),Or(Var 2,And(Not(Var 11),Or(Not(Var 11),And(Var 0,Or(Var 10,And(Var 9,Or(Not(Var 0),And(Not(Var 4),Or(Not(Var 12),And(Var 8,Or(Not(Var 6),And(Not(Var 12),Or(Not(Var 4),And(Not(Var 4),Or(Not(Var 8),And(Var 9,Or(Not(Var 5),And(Not(Var 9),Or(Not(Var 8),And(Not(Var 1),Or(Var 12,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 9),Or(Var 8,And(Not(Var 2),Not(Var 2)))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 8,And(Not(Var 12),Or(Not(Var 16),And(Not(Var 14),Or(Var 14,And(Not(Var 10),Or(Var 8,And(Var 10,Or(Var 15,And(Not(Var 14),Or(Not(Var 6),And(Not(Var 4),Or(Var 8,And(Var 1,Or(Not(Var 14),And(Var 2,Or(Not(Var 0),And(Not(Var 12),Or(Not(Var 10),And(Var 3,Or(Var 11,And(Var 8,Or(Var 5,And(Not(Var 1),Or(Var 11,And(Var 4,Or(Var 6,And(Not(Var 3),Or(Not(Var 4),And(Var 3,Or(Not(Var 2),And(Var 9,Or(Not(Var 11),And(Not(Var 3),Or(Var 5,And(Var 9,Or(Var 5,And(Not(Var 10),Or(Not(Var 14),And(Not(Var 16),Or(Var 13,And(Not(Var 13),Or(Var 5,Var 2)))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 5),Or(Not(Var 13),And(Not(Var 9),Or(Not(Var 0),And(Var 13,Or(Not(Var 9),And(Var 12,Or(Not(Var 13),And(Not(Var 13),Or(Var 7,And(Not(Var 1),Or(Not(Var 1),And(Not(Var 2),Or(Var 12,And(Not(Var 3),Or(Var 4,And(Var 6,Or(Var 12,And(Var 9,Or(Not(Var 5),And(Var 12,Or(Var 12,And(Not(Var 5),Or(Var 13,And(Not(Var 0),Or(Not(Var 4),And(Var 8,Or(Var 3,And(Var 8,Or(Not(Var 1),And(Not(Var 6),Or(Not(Var 9),And(Not(Var 1),Or(Var 5,And(Not(Var 10),Or(Not(Var 10),And(Not(Var 11),Or(Var 5,And(Var 8,Or(Var 7,And(Not(Var 8),Or(Not(Var 6),And(Var 12,Or(Not(Var 11),And(Var 13,Var 0))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Var 13,And(Not(Var 15),Or(Var 9,And(Var 11,Or(Var 13,And(Var 0,Or(Not(Var 9),And(Var 8,Or(Not(Var 4),And(Not(Var 17),Or(Var 0,And(Not(Var 14),Or(Var 4,And(Var 3,Or(Var 1,And(Not(Var 17),Or(Not(Var 9),And(Var 10,Or(Not(Var 9),And(Not(Var 7),Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 11),And(Not(Var 9),Or(Not(Var 14),And(Var 3,Or(Var 4,And(Not(Var 17),Or(Var 11,And(Not(Var 7),Or(Not(Var 16),And(Var 7,Or(Var 13,And(Var 6,Or(Var 11,And(Var 6,Or(Var 16,And(Var 9,Or(Not(Var 12),And(Var 1,Or(Var 5,And(Var 3,Or(Not(Var 0),And(Not(Var 12),Or(Var 3,Var 17)))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Var 2,And(Var 1,Or(Not(Var 3),And(Var 3,Or(Not(Var 4),And(Var 2,Or(Not(Var 2),And(Var 2,Or(Not(Var 4),And(Var 2,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 2),Or(Var 4,And(Not(Var 2),Or(Not(Var 1),And(Var 3,Or(Not(Var 3),And(Var 0,Or(Var 4,And(Var 1,Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 4),Or(Var 2,And(Not(Var 1),Or(Not(Var 2),And(Var 0,Or(Var 2,And(Not(Var 2),Or(Not(Var 2),And(Not(Var 0),Or(Var 3,And(Not(Var 3),Or(Var 4,And(Not(Var 1),Or(Var 4,And(Not(Var 3),Or(Var 0,And(Var 2,Or(Not(Var 0),And(Var 3,Or(Var 1,And(Var 0,Var 0))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 1,And(Not(Var 11),Or(Not(Var 13),And(Not(Var 8),Or(Var 0,And(Var 13,Or(Var 13,And(Not(Var 4),Or(Not(Var 7),And(Var 12,Or(Var 1,And(Var 12,Or(Not(Var 4),And(Var 8,Or(Var 5,And(Not(Var 6),Or(Var 11,And(Not(Var 4),Or(Not(Var 6),And(Var 10,Or(Not(Var 1),And(Not(Var 5),Or(Var 10,And(Var 10,Or(Not(Var 6),And(Not(Var 8),Or(Var 12,And(Not(Var 11),Or(Not(Var 1),And(Var 7,Or(Not(Var 11),And(Var 3,Or(Var 10,And(Not(Var 5),Or(Not(Var 3),And(Var 8,Or(Var 7,And(Not(Var 10),Or(Not(Var 10),And(Var 7,Or(Var 11,And(Var 8,Or(Not(Var 12),And(Not(Var 6),Or(Not(Var 13),And(Var 9,Or(Not(Var 3),Not(Var 8))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 3,Or(Not(Var 2),And(Var 6,Or(Not(Var 6),And(Var 6,Or(Not(Var 2),And(Not(Var 3),Or(Var 0,And(Not(Var 1),Or(Var 1,And(Not(Var 1),Or(Not(Var 2),And(Var 3,Or(Not(Var 5),And(Var 1,Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 1),And(Var 0,Or(Var 5,And(Not(Var 4),Or(Not(Var 6),And(Var 1,Or(Var 2,And(Var 5,Or(Not(Var 2),And(Var 7,Or(Not(Var 6),And(Not(Var 3),Or(Var 3,And(Not(Var 4),Or(Var 4,And(Var 4,Or(Not(Var 5),And(Var 2,Or(Var 0,And(Var 1,Or(Var 5,And(Var 5,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 3),And(Not(Var 7),Or(Var 2,And(Var 6,Or(Var 6,And(Var 0,Or(Not(Var 4),And(Var 6,Var 3))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 12),Or(Not(Var 7),And(Not(Var 9),Or(Not(Var 16),And(Not(Var 8),Or(Var 1,And(Var 15,Or(Not(Var 18),And(Not(Var 10),Or(Not(Var 5),And(Not(Var 19),Or(Not(Var 19),And(Var 0,Or(Var 2,And(Not(Var 17),Or(Not(Var 15),And(Not(Var 12),Or(Var 10,And(Var 4,Or(Var 9,And(Var 0,Or(Var 9,And(Not(Var 16),Or(Not(Var 10),And(Var 5,Or(Var 10,And(Not(Var 16),Or(Not(Var 11),And(Not(Var 11),Or(Var 12,And(Var 15,Or(Not(Var 18),And(Not(Var 17),Or(Not(Var 11),And(Not(Var 9),Or(Var 17,And(Not(Var 7),Or(Var 12,And(Not(Var 2),Or(Var 0,And(Not(Var 3),Or(Not(Var 17),And(Var 5,Or(Not(Var 13),And(Var 7,Or(Not(Var 15),And(Var 4,Or(Not(Var 12),And(Not(Var 14),Or(Var 11,Var 8)))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 5),Or(Var 9,And(Not(Var 2),Or(Not(Var 1),And(Not(Var 10),Or(Not(Var 7),And(Not(Var 8),Or(Not(Var 0),And(Var 6,Or(Not(Var 3),And(Var 6,Or(Var 9,And(Not(Var 6),Or(Var 3,And(Var 3,Or(Not(Var 6),And(Not(Var 4),Or(Not(Var 5),And(Var 3,Or(Not(Var 8),And(Not(Var 7),Or(Var 10,And(Not(Var 7),Or(Not(Var 3),And(Var 10,Or(Var 9,And(Var 4,Or(Not(Var 0),And(Var 10,Or(Not(Var 6),And(Var 0,Or(Var 7,And(Not(Var 7),Or(Var 0,And(Not(Var 7),Or(Var 0,And(Not(Var 9),Or(Not(Var 8),And(Var 4,Or(Var 10,And(Var 10,Or(Not(Var 8),And(Var 3,Or(Not(Var 1),And(Var 5,Or(Var 10,And(Not(Var 9),Or(Not(Var 2),And(Not(Var 7),Or(Not(Var 2),And(Var 1,Var 5))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 4),And(Var 2,Or(Not(Var 1),And(Not(Var 4),Or(Var 3,And(Var 3,Or(Var 1,And(Not(Var 1),Or(Var 4,And(Var 4,Or(Not(Var 0),And(Var 3,Or(Var 4,And(Not(Var 1),Or(Not(Var 2),And(Not(Var 0),Or(Var 0,And(Var 2,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 4),And(Var 4,Or(Var 0,And(Var 2,Or(Not(Var 1),And(Not(Var 4),Or(Var 1,And(Var 0,Or(Not(Var 0),And(Not(Var 2),Or(Var 2,And(Var 0,Or(Not(Var 3),And(Not(Var 2),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 3,Or(Not(Var 4),And(Var 2,Or(Var 4,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 4),Or(Not(Var 3),And(Var 3,Or(Not(Var 2),Not(Var 4))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 10),Or(Var 12,And(Var 8,Or(Var 6,And(Not(Var 7),Or(Var 11,And(Var 3,Or(Var 0,And(Var 11,Or(Not(Var 1),And(Var 13,Or(Not(Var 13),And(Var 3,Or(Not(Var 7),And(Not(Var 3),Or(Not(Var 4),And(Var 0,Or(Var 7,And(Var 7,Or(Not(Var 8),And(Not(Var 10),Or(Not(Var 1),And(Var 12,Or(Not(Var 4),And(Not(Var 7),Or(Not(Var 2),And(Var 13,Or(Not(Var 2),And(Not(Var 10),Or(Not(Var 9),And(Var 12,Or(Var 5,And(Not(Var 12),Or(Not(Var 11),And(Var 7,Or(Var 4,And(Var 2,Or(Not(Var 4),And(Var 8,Or(Var 10,And(Not(Var 13),Or(Not(Var 7),And(Not(Var 6),Or(Var 4,And(Var 3,Or(Not(Var 8),And(Var 6,Or(Var 9,And(Not(Var 13),Or(Not(Var 1),And(Not(Var 7),Or(Var 2,And(Var 11,Var 5))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Not(Var 5),And(Var 6,Or(Var 6,And(Not(Var 0),Or(Not(Var 3),And(Var 2,Or(Not(Var 1),And(Var 6,Or(Var 4,And(Not(Var 1),Or(Var 0,And(Not(Var 4),Or(Not(Var 5),And(Not(Var 4),Or(Not(Var 2),And(Not(Var 6),Or(Not(Var 6),And(Var 3,Or(Not(Var 2),And(Var 1,Or(Var 4,And(Var 4,Or(Not(Var 1),And(Not(Var 2),Or(Not(Var 3),And(Var 2,Or(Var 2,And(Not(Var 1),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 5),Or(Not(Var 2),And(Not(Var 1),Or(Var 0,And(Not(Var 0),Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 3),And(Not(Var 2),Or(Var 2,And(Var 4,Or(Var 0,And(Not(Var 1),Or(Var 2,And(Var 1,Or(Not(Var 6),And(Not(Var 6),Or(Var 6,And(Var 0,Or(Var 3,And(Not(Var 6),Or(Var 0,Var 1)))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 15,Or(Var 1,And(Var 18,Or(Not(Var 10),And(Not(Var 16),Or(Var 2,And(Not(Var 19),Or(Not(Var 0),And(Not(Var 9),Or(Not(Var 12),And(Var 17,Or(Not(Var 12),And(Not(Var 6),Or(Var 10,And(Var 2,Or(Not(Var 13),And(Not(Var 1),Or(Var 12,And(Var 1,Or(Var 14,And(Var 9,Or(Var 11,And(Var 7,Or(Var 19,And(Not(Var 15),Or(Not(Var 1),And(Not(Var 5),Or(Not(Var 6),And(Var 4,Or(Not(Var 10),And(Not(Var 19),Or(Var 17,And(Not(Var 5),Or(Not(Var 7),And(Var 17,Or(Var 18,And(Var 19,Or(Not(Var 6),And(Var 5,Or(Not(Var 9),And(Var 5,Or(Not(Var 10),And(Var 1,Or(Var 2,And(Not(Var 10),Or(Not(Var 5),And(Not(Var 1),Or(Not(Var 2),And(Var 4,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 2),And(Not(Var 17),Or(Not(Var 0),And(Var 5,Var 17))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 6),Or(Not(Var 17),And(Not(Var 5),Or(Not(Var 17),And(Var 0,Or(Var 3,And(Not(Var 8),Or(Not(Var 15),And(Var 13,Or(Var 11,And(Var 10,Or(Not(Var 4),And(Var 16,Or(Not(Var 10),And(Not(Var 19),Or(Var 1,And(Var 5,Or(Var 1,And(Not(Var 13),Or(Not(Var 19),And(Not(Var 13),Or(Not(Var 5),And(Var 2,Or(Not(Var 19),And(Var 10,Or(Not(Var 5),And(Not(Var 18),Or(Var 14,And(Var 19,Or(Not(Var 4),And(Var 20,Or(Not(Var 9),And(Not(Var 15),Or(Not(Var 7),And(Var 3,Or(Not(Var 15),And(Not(Var 16),Or(Var 12,And(Var 6,Or(Not(Var 12),And(Var 9,Or(Var 10,And(Var 1,Or(Var 20,And(Var 13,Or(Var 8,And(Var 9,Or(Var 10,And(Var 4,Or(Var 12,And(Var 16,Or(Var 17,And(Var 15,Or(Not(Var 8),And(Not(Var 5),Or(Not(Var 8),Not(Var 3))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 6,Or(Not(Var 8),And(Var 19,Or(Not(Var 12),And(Not(Var 12),Or(Var 10,And(Var 21,Or(Not(Var 0),And(Not(Var 20),Or(Var 5,And(Not(Var 10),Or(Var 21,And(Var 3,Or(Var 3,And(Var 1,Or(Not(Var 17),And(Var 13,Or(Not(Var 24),And(Not(Var 6),Or(Not(Var 4),And(Var 14,Or(Not(Var 24),And(Var 14,Or(Var 18,And(Not(Var 6),Or(Not(Var 14),And(Var 2,Or(Var 19,And(Not(Var 7),Or(Not(Var 0),And(Var 5,Or(Var 11,And(Var 9,Or(Var 5,And(Not(Var 18),Or(Var 5,And(Not(Var 13),Or(Not(Var 4),And(Var 14,Or(Var 11,And(Var 15,Or(Not(Var 14),And(Not(Var 22),Or(Var 11,And(Not(Var 20),Or(Not(Var 11),And(Var 24,Or(Not(Var 13),And(Not(Var 23),Or(Var 20,And(Not(Var 4),Or(Not(Var 22),And(Var 2,Or(Var 18,And(Not(Var 5),Or(Not(Var 16),And(Not(Var 11),Not(Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 12),Or(Not(Var 12),And(Not(Var 0),Or(Not(Var 12),And(Var 14,Or(Var 6,And(Var 12,Or(Var 4,And(Not(Var 16),Or(Not(Var 16),And(Var 8,Or(Not(Var 16),And(Not(Var 17),Or(Var 8,And(Not(Var 13),Or(Var 10,And(Var 4,Or(Not(Var 4),And(Not(Var 6),Or(Var 1,And(Not(Var 10),Or(Var 12,And(Not(Var 1),Or(Not(Var 15),And(Var 11,Or(Var 15,And(Var 13,Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 7),And(Not(Var 10),Or(Not(Var 14),And(Not(Var 8),Or(Var 11,And(Not(Var 13),Or(Var 15,And(Not(Var 2),Or(Not(Var 1),And(Var 6,Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 11),And(Not(Var 15),Or(Not(Var 6),And(Not(Var 5),Or(Var 14,And(Not(Var 10),Or(Var 1,And(Not(Var 18),Or(Not(Var 14),And(Var 1,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 0),And(Var 8,Or(Var 2,And(Not(Var 8),Or(Not(Var 4),Not(Var 10))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Var 19,And(Not(Var 22),Or(Var 10,And(Not(Var 2),Or(Var 17,And(Var 16,Or(Var 13,And(Var 6,Or(Var 14,And(Not(Var 2),Or(Var 9,And(Not(Var 6),Or(Not(Var 10),And(Var 22,Or(Not(Var 11),And(Var 15,Or(Not(Var 6),And(Var 14,Or(Not(Var 22),And(Var 9,Or(Var 9,And(Not(Var 18),Or(Var 17,And(Not(Var 11),Or(Not(Var 13),And(Var 12,Or(Var 12,And(Not(Var 8),Or(Not(Var 4),And(Not(Var 16),Or(Var 22,And(Var 2,Or(Var 12,And(Not(Var 1),Or(Not(Var 13),And(Not(Var 1),Or(Var 12,And(Not(Var 10),Or(Not(Var 7),And(Not(Var 20),Or(Not(Var 8),And(Var 0,Or(Var 17,And(Var 19,Or(Var 9,And(Not(Var 9),Or(Not(Var 16),And(Not(Var 3),Or(Not(Var 11),And(Var 1,Or(Not(Var 18),And(Var 17,Or(Var 3,And(Var 2,Or(Not(Var 9),And(Not(Var 7),Or(Not(Var 13),And(Var 0,Var 16))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 8,Or(Var 3,And(Var 7,Or(Not(Var 5),And(Var 11,Or(Not(Var 4),And(Var 10,Or(Var 12,And(Not(Var 6),Or(Var 2,And(Var 5,Or(Not(Var 5),And(Not(Var 13),Or(Var 1,And(Not(Var 10),Or(Var 1,And(Not(Var 12),Or(Not(Var 11),And(Not(Var 9),Or(Var 10,And(Var 5,Or(Var 7,And(Not(Var 12),Or(Var 13,And(Not(Var 2),Or(Not(Var 4),And(Not(Var 6),Or(Var 4,And(Not(Var 2),Or(Var 7,And(Not(Var 1),Or(Not(Var 12),And(Var 10,Or(Var 13,And(Not(Var 1),Or(Var 5,And(Var 1,Or(Not(Var 4),And(Var 7,Or(Var 5,And(Not(Var 11),Or(Not(Var 0),And(Not(Var 7),Or(Var 1,And(Not(Var 6),Or(Not(Var 11),And(Var 10,Or(Not(Var 6),And(Var 1,Or(Not(Var 5),And(Var 11,Or(Var 5,And(Var 9,Or(Not(Var 0),And(Not(Var 1),Or(Var 4,And(Not(Var 5),Or(Var 1,And(Not(Var 13),Or(Var 12,Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 9,Or(Not(Var 24),And(Var 1,Or(Var 20,And(Var 9,Or(Var 11,And(Not(Var 21),Or(Var 7,And(Not(Var 11),Or(Not(Var 7),And(Not(Var 14),Or(Not(Var 6),And(Not(Var 14),Or(Var 24,And(Var 2,Or(Var 5,And(Var 22,Or(Not(Var 12),And(Not(Var 17),Or(Var 9,And(Var 25,Or(Not(Var 14),And(Var 15,Or(Var 12,And(Var 24,Or(Var 13,And(Var 20,Or(Not(Var 13),And(Not(Var 9),Or(Var 0,And(Var 12,Or(Var 3,And(Var 2,Or(Var 18,And(Var 6,Or(Not(Var 12),And(Var 4,Or(Var 14,And(Var 7,Or(Not(Var 15),And(Not(Var 10),Or(Not(Var 4),And(Not(Var 23),Or(Not(Var 2),And(Not(Var 21),Or(Not(Var 19),And(Var 6,Or(Not(Var 9),And(Var 17,Or(Var 1,And(Not(Var 19),Or(Not(Var 14),And(Var 16,Or(Var 15,And(Not(Var 8),Or(Not(Var 16),And(Var 14,Or(Not(Var 8),And(Not(Var 2),Or(Not(Var 8),And(Var 2,Var 15))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 3),Or(Not(Var 4),And(Var 4,Or(Not(Var 1),And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 5),And(Not(Var 2),Or(Var 1,And(Var 4,Or(Var 3,And(Var 5,Or(Var 4,And(Var 2,Or(Not(Var 2),And(Not(Var 0),Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 5),And(Not(Var 2),Or(Var 3,And(Var 5,Or(Not(Var 0),And(Var 5,Or(Var 5,And(Var 4,Or(Not(Var 1),And(Var 1,Or(Not(Var 5),And(Var 3,Or(Var 2,And(Var 2,Or(Not(Var 0),And(Var 3,Or(Var 3,And(Not(Var 0),Or(Not(Var 3),And(Not(Var 2),Or(Var 4,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 0),Or(Var 4,And(Not(Var 2),Or(Var 4,And(Not(Var 1),Or(Not(Var 0),And(Var 3,Or(Var 1,And(Var 4,Or(Not(Var 2),And(Var 5,Or(Var 5,And(Var 4,Or(Not(Var 2),And(Not(Var 2),Or(Var 4,And(Var 4,Or(Var 0,And(Var 4,Or(Var 0,Var 2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 8,Or(Not(Var 11),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 2),Or(Not(Var 9),And(Var 12,Or(Var 0,And(Var 1,Or(Not(Var 0),And(Var 8,Or(Not(Var 3),And(Not(Var 6),Or(Var 12,And(Not(Var 3),Or(Not(Var 8),And(Not(Var 9),Or(Not(Var 10),And(Not(Var 4),Or(Var 1,And(Var 1,Or(Var 13,And(Not(Var 10),Or(Not(Var 13),And(Not(Var 13),Or(Var 3,And(Var 7,Or(Not(Var 13),And(Var 7,Or(Var 4,And(Not(Var 6),Or(Not(Var 12),And(Var 6,Or(Var 11,And(Var 15,Or(Not(Var 4),And(Var 5,Or(Var 7,And(Not(Var 1),Or(Var 2,And(Not(Var 9),Or(Not(Var 14),And(Not(Var 13),Or(Not(Var 5),And(Not(Var 5),Or(Not(Var 0),And(Not(Var 10),Or(Not(Var 12),And(Not(Var 8),Or(Var 7,And(Not(Var 4),Or(Not(Var 10),And(Not(Var 0),Or(Not(Var 9),And(Not(Var 12),Or(Not(Var 5),And(Not(Var 5),Or(Var 1,And(Var 4,Or(Not(Var 10),And(Var 4,Or(Not(Var 1),And(Not(Var 5),Not(Var 11)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 11),And(Not(Var 13),Or(Var 13,And(Var 5,Or(Not(Var 2),And(Var 26,Or(Var 22,And(Var 19,Or(Not(Var 4),And(Var 0,Or(Var 15,And(Var 18,Or(Not(Var 23),And(Not(Var 12),Or(Var 0,And(Var 5,Or(Var 3,And(Var 18,Or(Not(Var 2),And(Not(Var 9),Or(Var 23,And(Not(Var 9),Or(Not(Var 3),And(Not(Var 26),Or(Not(Var 8),And(Var 9,Or(Not(Var 9),And(Not(Var 17),Or(Not(Var 16),And(Var 6,Or(Not(Var 5),And(Not(Var 12),Or(Var 12,And(Not(Var 13),Or(Not(Var 23),And(Var 11,Or(Not(Var 16),And(Var 10,Or(Not(Var 14),And(Not(Var 5),Or(Not(Var 19),And(Var 15,Or(Var 9,And(Not(Var 13),Or(Var 5,And(Not(Var 11),Or(Not(Var 6),And(Not(Var 19),Or(Var 0,And(Var 7,Or(Var 12,And(Var 8,Or(Not(Var 16),And(Var 23,Or(Var 0,And(Not(Var 17),Or(Not(Var 12),And(Var 9,Or(Var 20,And(Var 14,Or(Var 5,Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 3,Or(Not(Var 6),And(Not(Var 5),Or(Var 17,And(Var 13,Or(Not(Var 15),And(Var 6,Or(Var 2,And(Var 9,Or(Var 8,And(Var 13,Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 3),And(Not(Var 12),Or(Not(Var 15),And(Not(Var 9),Or(Var 4,And(Var 4,Or(Var 3,And(Not(Var 4),Or(Var 11,And(Var 18,Or(Not(Var 14),And(Var 9,Or(Var 0,And(Var 2,Or(Var 5,And(Var 0,Or(Not(Var 12),And(Not(Var 8),Or(Not(Var 1),And(Not(Var 2),Or(Not(Var 9),And(Not(Var 14),Or(Var 3,And(Not(Var 6),Or(Var 14,And(Not(Var 17),Or(Not(Var 13),And(Var 18,Or(Var 0,And(Not(Var 18),Or(Not(Var 9),And(Not(Var 0),Or(Var 11,And(Not(Var 0),Or(Var 14,And(Var 7,Or(Var 18,And(Not(Var 1),Or(Not(Var 14),And(Var 1,Or(Var 1,And(Var 12,Or(Not(Var 5),And(Var 11,Or(Var 2,And(Var 10,Or(Not(Var 9),And(Var 5,Or(Var 9,And(Not(Var 14),Or(Var 7,And(Not(Var 0),Not(Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 2),Or(Not(Var 14),And(Not(Var 8),Or(Var 13,And(Var 10,Or(Var 5,And(Not(Var 5),Or(Var 1,And(Var 10,Or(Not(Var 1),And(Var 1,Or(Var 13,And(Var 0,Or(Not(Var 4),And(Var 10,Or(Not(Var 0),And(Not(Var 3),Or(Var 8,And(Var 7,Or(Var 12,And(Not(Var 13),Or(Not(Var 3),And(Not(Var 3),Or(Var 0,And(Var 11,Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Var 5,Or(Not(Var 12),And(Not(Var 12),Or(Var 1,And(Var 11,Or(Not(Var 8),And(Var 13,Or(Not(Var 12),And(Not(Var 5),Or(Var 12,And(Not(Var 7),Or(Not(Var 5),And(Var 0,Or(Var 1,And(Not(Var 9),Or(Var 4,And(Not(Var 1),Or(Not(Var 6),And(Var 10,Or(Not(Var 5),And(Var 1,Or(Not(Var 9),And(Var 0,Or(Var 2,And(Not(Var 9),Or(Var 0,And(Var 1,Or(Var 13,And(Var 2,Or(Var 2,And(Not(Var 13),Or(Not(Var 13),And(Var 14,Or(Not(Var 11),And(Var 10,Or(Var 9,And(Var 0,Or(Var 7,Var 10)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 27),Or(Var 13,And(Not(Var 3),Or(Var 26,And(Var 29,Or(Not(Var 0),And(Var 14,Or(Not(Var 6),And(Not(Var 12),Or(Not(Var 23),And(Not(Var 13),Or(Var 5,And(Var 23,Or(Var 8,And(Var 10,Or(Var 18,And(Var 6,Or(Var 8,And(Not(Var 1),Or(Var 27,And(Not(Var 21),Or(Var 18,And(Not(Var 17),Or(Not(Var 23),And(Var 8,Or(Var 15,And(Not(Var 6),Or(Not(Var 6),And(Not(Var 28),Or(Not(Var 5),And(Not(Var 5),Or(Var 11,And(Var 22,Or(Not(Var 1),And(Var 17,Or(Var 2,And(Not(Var 19),Or(Var 31,And(Var 7,Or(Not(Var 20),And(Var 16,Or(Not(Var 10),And(Var 29,Or(Not(Var 8),And(Var 15,Or(Var 12,And(Var 19,Or(Not(Var 20),And(Not(Var 12),Or(Var 19,And(Not(Var 0),Or(Var 29,And(Not(Var 28),Or(Not(Var 13),And(Var 6,Or(Not(Var 29),And(Var 22,Or(Var 4,And(Not(Var 0),Or(Not(Var 19),And(Not(Var 32),Or(Var 19,And(Var 13,Or(Var 1,And(Not(Var 5),Or(Var 6,And(Var 25,Var 14))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 11),Or(Var 4,And(Not(Var 9),Or(Var 7,And(Var 0,Or(Var 5,And(Not(Var 4),Or(Var 2,And(Var 4,Or(Var 2,And(Not(Var 10),Or(Not(Var 2),And(Not(Var 7),Or(Var 0,And(Not(Var 3),Or(Not(Var 6),And(Not(Var 1),Or(Var 10,And(Var 1,Or(Var 9,And(Not(Var 9),Or(Var 8,And(Var 10,Or(Not(Var 1),And(Var 9,Or(Not(Var 5),And(Not(Var 8),Or(Not(Var 4),And(Var 5,Or(Not(Var 5),And(Var 9,Or(Not(Var 0),And(Var 11,Or(Var 0,And(Not(Var 5),Or(Var 10,And(Var 6,Or(Not(Var 6),And(Not(Var 4),Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 9),And(Not(Var 10),Or(Not(Var 11),And(Var 4,Or(Not(Var 0),And(Var 8,Or(Var 4,And(Not(Var 2),Or(Not(Var 9),And(Not(Var 0),Or(Var 11,And(Var 1,Or(Var 8,And(Not(Var 0),Or(Var 4,And(Not(Var 7),Or(Var 3,And(Not(Var 4),Or(Not(Var 0),And(Var 0,Or(Var 2,And(Not(Var 9),Or(Not(Var 5),And(Var 6,Or(Var 11,And(Not(Var 9),Or(Not(Var 0),Not(Var 6))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 29),Or(Not(Var 3),And(Not(Var 22),Or(Not(Var 29),And(Not(Var 27),Or(Not(Var 19),And(Var 19,Or(Not(Var 29),And(Var 13,Or(Var 8,And(Not(Var 21),Or(Var 20,And(Not(Var 14),Or(Not(Var 14),And(Not(Var 7),Or(Var 11,And(Not(Var 22),Or(Not(Var 2),And(Var 20,Or(Var 2,And(Var 2,Or(Var 16,And(Not(Var 26),Or(Var 18,And(Var 24,Or(Not(Var 13),And(Not(Var 2),Or(Var 29,And(Not(Var 24),Or(Not(Var 24),And(Not(Var 20),Or(Not(Var 1),And(Not(Var 9),Or(Not(Var 4),And(Not(Var 28),Or(Var 6,And(Not(Var 18),Or(Not(Var 0),And(Not(Var 6),Or(Var 0,And(Not(Var 22),Or(Not(Var 6),And(Not(Var 10),Or(Var 0,And(Not(Var 26),Or(Var 7,And(Var 13,Or(Not(Var 0),And(Not(Var 10),Or(Var 30,And(Not(Var 26),Or(Not(Var 14),And(Not(Var 16),Or(Var 4,And(Not(Var 8),Or(Var 29,And(Not(Var 22),Or(Var 14,And(Var 12,Or(Var 21,And(Var 7,Or(Not(Var 22),And(Var 24,Or(Var 29,And(Not(Var 31),Or(Var 14,And(Not(Var 12),Or(Var 25,And(Not(Var 20),Not(Var 29)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 12,Or(Not(Var 6),And(Not(Var 18),Or(Not(Var 8),And(Var 19,Or(Var 2,And(Var 9,Or(Var 9,And(Var 10,Or(Var 16,And(Not(Var 7),Or(Var 15,And(Var 16,Or(Var 8,And(Var 2,Or(Not(Var 9),And(Var 3,Or(Var 9,And(Var 12,Or(Not(Var 11),And(Var 9,Or(Not(Var 8),And(Not(Var 4),Or(Not(Var 1),And(Not(Var 12),Or(Var 18,And(Var 14,Or(Not(Var 19),And(Not(Var 11),Or(Var 5,And(Var 8,Or(Not(Var 12),And(Var 15,Or(Var 13,And(Var 19,Or(Var 16,And(Not(Var 19),Or(Not(Var 16),And(Var 8,Or(Not(Var 10),And(Not(Var 4),Or(Not(Var 13),And(Var 15,Or(Var 7,And(Var 19,Or(Not(Var 10),And(Not(Var 1),Or(Not(Var 4),And(Var 2,Or(Not(Var 10),And(Not(Var 16),Or(Not(Var 12),And(Not(Var 13),Or(Not(Var 16),And(Var 13,Or(Var 16,And(Var 4,Or(Var 7,And(Var 16,Or(Not(Var 17),And(Var 4,Or(Not(Var 13),And(Not(Var 5),Or(Not(Var 15),And(Var 5,Or(Var 0,And(Var 1,Or(Not(Var 6),And(Var 16,Or(Var 14,Var 15)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 4),Or(Not(Var 5),And(Var 22,Or(Var 7,And(Var 2,Or(Var 2,And(Var 29,Or(Var 12,And(Not(Var 24),Or(Not(Var 7),And(Var 16,Or(Var 23,And(Var 9,Or(Var 21,And(Var 26,Or(Var 17,And(Not(Var 18),Or(Not(Var 15),And(Not(Var 18),Or(Not(Var 23),And(Var 26,Or(Not(Var 3),And(Not(Var 20),Or(Var 28,And(Var 14,Or(Not(Var 4),And(Not(Var 12),Or(Var 15,And(Var 26,Or(Var 29,And(Var 23,Or(Var 17,And(Not(Var 22),Or(Var 14,And(Var 6,Or(Var 12,And(Not(Var 17),Or(Not(Var 24),And(Not(Var 21),Or(Var 16,And(Var 21,Or(Var 13,And(Var 5,Or(Var 12,And(Not(Var 3),Or(Var 26,And(Not(Var 9),Or(Not(Var 20),And(Not(Var 12),Or(Var 25,And(Not(Var 18),Or(Not(Var 13),And(Var 27,Or(Not(Var 11),And(Var 7,Or(Var 23,And(Var 10,Or(Not(Var 6),And(Var 29,Or(Var 13,And(Not(Var 11),Or(Not(Var 25),And(Not(Var 21),Or(Var 1,And(Var 27,Or(Var 10,And(Var 14,Or(Var 11,And(Not(Var 27),Or(Var 27,And(Var 8,Var 28))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Var 1,And(Not(Var 2),Or(Var 1,And(Not(Var 3),Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 1),And(Not(Var 5),Or(Not(Var 3),And(Not(Var 3),Or(Var 4,And(Var 3,Or(Var 4,And(Var 3,Or(Not(Var 0),And(Var 5,Or(Not(Var 5),And(Not(Var 2),Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 1),And(Not(Var 0),Or(Var 4,And(Var 3,Or(Not(Var 2),And(Var 0,Or(Not(Var 4),And(Not(Var 3),Or(Not(Var 4),And(Var 3,Or(Var 0,And(Var 5,Or(Var 5,And(Var 4,Or(Var 1,And(Not(Var 2),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 4),And(Var 1,Or(Var 0,And(Var 5,Or(Var 4,And(Not(Var 0),Or(Var 3,And(Not(Var 4),Or(Var 0,And(Var 4,Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 4,And(Var 0,Or(Not(Var 2),And(Not(Var 0),Or(Var 4,And(Var 5,Or(Var 5,And(Not(Var 5),Or(Not(Var 4),And(Not(Var 5),Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Var 3,Or(Not(Var 4),Not(Var 1))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 2),Or(Not(Var 1),And(Var 6,Or(Not(Var 6),And(Not(Var 3),Or(Var 0,And(Not(Var 1),Or(Var 4,And(Var 2,Or(Not(Var 0),And(Var 4,Or(Var 5,And(Var 4,Or(Not(Var 3),And(Not(Var 1),Or(Var 5,And(Not(Var 1),Or(Var 1,And(Not(Var 6),Or(Var 3,And(Not(Var 5),Or(Var 4,And(Not(Var 5),Or(Var 5,And(Not(Var 0),Or(Var 2,And(Not(Var 5),Or(Not(Var 2),And(Var 1,Or(Var 5,And(Var 6,Or(Not(Var 2),And(Not(Var 0),Or(Not(Var 3),And(Not(Var 0),Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 5),And(Var 6,Or(Not(Var 3),And(Not(Var 2),Or(Var 6,And(Var 0,Or(Not(Var 5),And(Not(Var 3),Or(Not(Var 1),And(Var 5,Or(Var 4,And(Not(Var 2),Or(Not(Var 2),And(Not(Var 3),Or(Var 0,And(Not(Var 6),Or(Var 4,And(Not(Var 5),Or(Var 1,And(Var 3,Or(Var 2,And(Not(Var 4),Or(Var 4,And(Not(Var 6),Or(Var 6,And(Var 1,Or(Not(Var 2),And(Var 6,Or(Var 2,And(Not(Var 3),Or(Not(Var 4),And(Var 5,Or(Var 4,And(Not(Var 0),Or(Not(Var 3),And(Not(Var 5),Not(Var 2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 9,Or(Var 31,And(Var 21,Or(Not(Var 14),And(Not(Var 29),Or(Var 11,And(Not(Var 7),Or(Not(Var 30),And(Var 6,Or(Not(Var 31),And(Not(Var 29),Or(Var 10,And(Not(Var 30),Or(Not(Var 11),And(Var 0,Or(Var 30,And(Var 13,Or(Var 29,And(Var 26,Or(Var 14,And(Not(Var 6),Or(Not(Var 23),And(Var 18,Or(Not(Var 5),And(Var 21,Or(Var 11,And(Var 28,Or(Var 26,And(Var 11,Or(Var 32,And(Var 23,Or(Not(Var 32),And(Not(Var 26),Or(Var 20,And(Not(Var 12),Or(Not(Var 34),And(Not(Var 7),Or(Var 0,And(Var 13,Or(Var 31,And(Var 4,Or(Not(Var 11),And(Var 33,Or(Var 6,And(Not(Var 3),Or(Not(Var 25),And(Not(Var 19),Or(Var 20,And(Var 18,Or(Not(Var 14),And(Not(Var 11),Or(Var 18,And(Not(Var 10),Or(Not(Var 12),And(Not(Var 5),Or(Var 26,And(Var 25,Or(Not(Var 0),And(Var 34,Or(Not(Var 3),And(Not(Var 1),Or(Var 3,And(Not(Var 34),Or(Not(Var 4),And(Var 23,Or(Var 21,And(Var 2,Or(Var 8,And(Var 17,Or(Var 24,And(Var 5,Or(Var 8,And(Not(Var 8),Or(Var 17,Var 24)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 7),And(Var 37,Or(Var 34,And(Var 19,Or(Not(Var 4),And(Var 1,Or(Var 15,And(Not(Var 4),Or(Not(Var 2),And(Var 21,Or(Var 15,And(Not(Var 11),Or(Var 19,And(Var 35,Or(Var 4,And(Not(Var 29),Or(Var 19,And(Var 18,Or(Not(Var 4),And(Not(Var 35),Or(Var 13,And(Var 11,Or(Var 37,And(Not(Var 11),Or(Var 18,And(Var 30,Or(Not(Var 36),And(Not(Var 16),Or(Not(Var 33),And(Var 26,Or(Var 27,And(Var 18,Or(Not(Var 20),And(Not(Var 17),Or(Var 29,And(Not(Var 11),Or(Not(Var 13),And(Not(Var 36),Or(Var 34,And(Var 30,Or(Var 9,And(Var 35,Or(Var 9,And(Not(Var 16),Or(Var 34,And(Not(Var 36),Or(Var 16,And(Not(Var 12),Or(Var 15,And(Var 14,Or(Var 21,And(Not(Var 33),Or(Var 23,And(Not(Var 23),Or(Not(Var 3),And(Var 35,Or(Var 10,And(Var 33,Or(Var 16,And(Var 35,Or(Var 30,And(Not(Var 31),Or(Not(Var 1),And(Not(Var 22),Or(Not(Var 2),And(Var 12,Or(Not(Var 37),And(Not(Var 8),Or(Var 26,And(Var 27,Or(Var 5,And(Var 12,Or(Var 37,And(Not(Var 16),Not(Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 24),Or(Var 7,And(Not(Var 6),Or(Var 29,And(Var 13,Or(Not(Var 5),And(Var 26,Or(Var 5,And(Var 29,Or(Var 11,And(Not(Var 17),Or(Var 21,And(Not(Var 8),Or(Var 15,And(Not(Var 8),Or(Not(Var 15),And(Var 30,Or(Var 29,And(Var 9,Or(Var 10,And(Not(Var 6),Or(Not(Var 0),And(Not(Var 24),Or(Var 30,And(Var 5,Or(Not(Var 1),And(Var 30,Or(Not(Var 3),And(Not(Var 23),Or(Var 27,And(Var 8,Or(Not(Var 11),And(Not(Var 28),Or(Var 12,And(Not(Var 18),Or(Var 0,And(Var 3,Or(Var 28,And(Not(Var 24),Or(Var 12,And(Not(Var 4),Or(Var 26,And(Not(Var 6),Or(Not(Var 6),And(Var 18,Or(Not(Var 28),And(Var 30,Or(Not(Var 1),And(Var 14,Or(Var 6,And(Not(Var 27),Or(Not(Var 14),And(Var 28,Or(Var 1,And(Var 22,Or(Var 25,And(Not(Var 18),Or(Not(Var 10),And(Var 13,Or(Var 6,And(Var 23,Or(Var 25,And(Var 3,Or(Not(Var 26),And(Var 24,Or(Not(Var 27),And(Not(Var 20),Or(Var 30,And(Not(Var 17),Or(Var 30,And(Not(Var 30),Or(Not(Var 21),And(Not(Var 18),Or(Var 14,And(Not(Var 15),Or(Var 5,Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Var 0,And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Not(Var 2),And(Var 0,Or(Not(Var 2),And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 2),Or(Not(Var 1),And(Var 0,Or(Not(Var 2),And(Not(Var 1),Or(Var 2,And(Var 0,Or(Var 1,And(Var 1,Or(Var 0,And(Var 2,Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 0),Or(Var 2,And(Not(Var 1),Or(Not(Var 2),And(Var 2,Or(Var 1,And(Var 0,Or(Var 0,And(Not(Var 1),Or(Var 2,And(Var 0,Or(Not(Var 2),And(Var 1,Or(Var 2,And(Not(Var 1),Or(Var 0,And(Var 2,Or(Not(Var 1),And(Not(Var 2),Or(Var 0,And(Not(Var 2),Or(Not(Var 0),And(Var 2,Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 1),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 1,Or(Var 2,And(Var 0,Or(Var 2,And(Var 2,Or(Not(Var 1),And(Var 1,Or(Var 2,And(Var 0,Or(Not(Var 2),And(Not(Var 2),Not(Var 2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 12),And(Not(Var 5),Or(Not(Var 9),And(Not(Var 11),Or(Not(Var 3),And(Not(Var 8),Or(Var 4,And(Not(Var 8),Or(Var 6,And(Not(Var 0),Or(Var 9,And(Var 8,Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 1),And(Var 3,Or(Var 3,And(Var 8,Or(Var 9,And(Not(Var 11),Or(Var 12,And(Var 7,Or(Var 0,And(Not(Var 5),Or(Not(Var 9),And(Var 11,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 12),And(Var 7,Or(Not(Var 10),And(Not(Var 2),Or(Var 10,And(Not(Var 0),Or(Var 4,And(Var 12,Or(Var 6,And(Var 8,Or(Var 3,And(Var 11,Or(Not(Var 12),And(Not(Var 11),Or(Not(Var 1),And(Not(Var 11),Or(Not(Var 9),And(Not(Var 6),Or(Var 8,And(Var 0,Or(Var 1,And(Var 5,Or(Var 9,And(Var 7,Or(Var 2,And(Var 3,Or(Var 8,And(Var 1,Or(Var 9,And(Var 5,Or(Not(Var 4),And(Not(Var 11),Or(Var 3,And(Var 4,Or(Not(Var 7),And(Var 9,Or(Not(Var 11),And(Var 3,Or(Var 1,And(Var 9,Or(Not(Var 7),And(Var 9,Or(Var 0,And(Not(Var 2),Or(Var 6,And(Not(Var 6),Or(Var 4,And(Not(Var 3),Or(Not(Var 1),Not(Var 11))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 4),And(Var 0,Or(Var 2,And(Not(Var 4),Or(Var 1,And(Var 2,Or(Var 2,And(Not(Var 0),Or(Not(Var 0),And(Var 3,Or(Not(Var 4),And(Not(Var 3),Or(Var 4,And(Not(Var 4),Or(Var 1,And(Not(Var 0),Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 3),And(Var 4,Or(Var 2,And(Not(Var 1),Or(Var 0,And(Var 3,Or(Var 0,And(Not(Var 4),Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 2),Or(Var 4,And(Not(Var 0),Or(Var 2,And(Var 0,Or(Var 4,And(Not(Var 2),Or(Var 2,And(Not(Var 2),Or(Not(Var 1),And(Var 3,Or(Not(Var 2),And(Var 3,Or(Var 4,And(Var 2,Or(Not(Var 2),And(Var 0,Or(Var 0,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 3),Or(Var 2,And(Not(Var 0),Or(Not(Var 2),And(Not(Var 4),Or(Not(Var 0),And(Var 2,Or(Not(Var 0),And(Var 0,Or(Var 4,And(Not(Var 0),Or(Var 2,And(Var 2,Or(Not(Var 1),And(Var 3,Or(Not(Var 1),And(Var 4,Or(Not(Var 2),And(Not(Var 2),Or(Not(Var 0),And(Var 2,Or(Not(Var 3),And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 2,And(Var 1,Var 0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 7),And(Var 7,Or(Var 7,And(Not(Var 8),Or(Var 7,And(Var 0,Or(Not(Var 9),And(Not(Var 2),Or(Not(Var 9),And(Var 9,Or(Not(Var 5),And(Not(Var 0),Or(Not(Var 7),And(Var 4,Or(Not(Var 3),And(Not(Var 7),Or(Not(Var 8),And(Not(Var 6),Or(Var 5,And(Not(Var 5),Or(Var 7,And(Not(Var 6),Or(Var 9,And(Not(Var 6),Or(Var 8,And(Not(Var 4),Or(Not(Var 8),And(Var 6,Or(Not(Var 6),And(Var 7,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 1),And(Var 5,Or(Var 2,And(Var 8,Or(Var 0,And(Not(Var 7),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 6),And(Not(Var 7),Or(Var 7,And(Not(Var 0),Or(Not(Var 2),And(Not(Var 5),Or(Var 7,And(Not(Var 1),Or(Var 1,And(Not(Var 5),Or(Not(Var 5),And(Not(Var 1),Or(Var 7,And(Not(Var 4),Or(Var 4,And(Var 3,Or(Not(Var 3),And(Not(Var 3),Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 0),And(Var 6,Or(Not(Var 8),And(Var 1,Or(Not(Var 7),And(Var 6,Or(Var 7,And(Not(Var 5),Or(Var 7,And(Var 2,Or(Var 9,And(Var 0,Or(Not(Var 5),And(Not(Var 1),Or(Var 5,And(Not(Var 6),Or(Not(Var 9),Not(Var 7))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 1,And(Not(Var 7),Or(Var 24,And(Not(Var 10),Or(Var 25,And(Var 9,Or(Not(Var 23),And(Not(Var 13),Or(Var 9,And(Var 8,Or(Not(Var 12),And(Not(Var 10),Or(Not(Var 25),And(Var 18,Or(Var 28,And(Var 27,Or(Not(Var 20),And(Var 27,Or(Not(Var 2),And(Var 7,Or(Not(Var 20),And(Var 20,Or(Var 19,And(Not(Var 18),Or(Var 6,And(Not(Var 3),Or(Var 5,And(Var 11,Or(Var 28,And(Var 10,Or(Not(Var 12),And(Var 7,Or(Var 27,And(Var 5,Or(Not(Var 4),And(Var 20,Or(Var 5,And(Var 15,Or(Var 16,And(Var 1,Or(Not(Var 21),And(Not(Var 23),Or(Var 8,And(Not(Var 23),Or(Not(Var 15),And(Not(Var 28),Or(Not(Var 5),And(Not(Var 4),Or(Not(Var 28),And(Not(Var 9),Or(Var 8,And(Not(Var 7),Or(Var 12,And(Var 13,Or(Not(Var 0),And(Not(Var 30),Or(Not(Var 16),And(Var 18,Or(Var 16,And(Var 1,Or(Not(Var 14),And(Var 20,Or(Not(Var 23),And(Var 22,Or(Var 2,And(Var 10,Or(Not(Var 24),And(Var 16,Or(Not(Var 3),And(Var 22,Or(Not(Var 4),And(Not(Var 9),Or(Not(Var 27),And(Var 12,Or(Var 4,And(Var 8,Or(Not(Var 10),And(Var 25,Or(Var 26,And(Var 27,Var 10))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Not(Var 6),And(Not(Var 7),Or(Var 8,And(Not(Var 21),Or(Var 13,And(Var 11,Or(Var 8,And(Not(Var 11),Or(Var 22,And(Not(Var 9),Or(Not(Var 22),And(Not(Var 15),Or(Not(Var 0),And(Not(Var 13),Or(Var 3,And(Not(Var 16),Or(Not(Var 7),And(Var 18,Or(Not(Var 20),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Var 19,Or(Var 13,And(Not(Var 15),Or(Not(Var 12),And(Var 7,Or(Not(Var 9),And(Not(Var 18),Or(Var 2,And(Not(Var 4),Or(Var 11,And(Not(Var 20),Or(Var 4,And(Not(Var 9),Or(Var 0,And(Not(Var 14),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 3),Or(Var 0,And(Not(Var 2),Or(Not(Var 11),And(Not(Var 18),Or(Not(Var 6),And(Not(Var 18),Or(Var 1,And(Not(Var 11),Or(Var 1,And(Var 21,Or(Not(Var 5),And(Var 22,Or(Var 21,And(Var 11,Or(Var 13,And(Not(Var 9),Or(Var 8,And(Not(Var 22),Or(Not(Var 22),And(Not(Var 7),Or(Not(Var 4),And(Var 18,Or(Not(Var 0),And(Not(Var 3),Or(Var 19,And(Not(Var 14),Or(Var 12,And(Var 10,Or(Not(Var 11),And(Not(Var 22),Or(Not(Var 16),And(Not(Var 2),Or(Var 11,And(Var 17,Or(Var 4,And(Var 4,Or(Not(Var 3),And(Var 17,Or(Not(Var 13),Not(Var 5))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 15,Or(Not(Var 3),And(Not(Var 10),Or(Var 1,And(Not(Var 15),Or(Not(Var 5),And(Not(Var 1),Or(Var 6,And(Not(Var 15),Or(Not(Var 1),And(Not(Var 13),Or(Var 12,And(Var 13,Or(Var 10,And(Var 5,Or(Not(Var 0),And(Not(Var 13),Or(Not(Var 14),And(Var 12,Or(Not(Var 2),And(Var 15,Or(Not(Var 15),And(Var 1,Or(Var 3,And(Var 5,Or(Var 10,And(Var 7,Or(Var 12,And(Var 9,Or(Var 12,And(Var 1,Or(Var 13,And(Var 11,Or(Var 3,And(Var 6,Or(Var 9,And(Not(Var 12),Or(Not(Var 11),And(Not(Var 8),Or(Not(Var 3),And(Not(Var 9),Or(Var 9,And(Var 5,Or(Var 8,And(Var 11,Or(Not(Var 11),And(Var 3,Or(Not(Var 1),And(Not(Var 12),Or(Var 7,And(Var 15,Or(Var 6,And(Not(Var 11),Or(Not(Var 13),And(Not(Var 6),Or(Not(Var 1),And(Var 12,Or(Var 0,And(Not(Var 11),Or(Not(Var 7),And(Var 12,Or(Not(Var 13),And(Var 11,Or(Var 10,And(Var 12,Or(Not(Var 9),And(Not(Var 10),Or(Not(Var 12),And(Not(Var 8),Or(Var 13,And(Var 10,Or(Not(Var 3),And(Var 2,Or(Var 14,And(Var 14,Or(Var 4,And(Var 5,Or(Not(Var 9),And(Not(Var 13),Or(Var 5,And(Var 0,Or(Var 0,And(Var 10,Var 12))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Not(Var 3),And(Not(Var 3),Or(Not(Var 5),And(Not(Var 0),Or(Not(Var 2),And(Not(Var 3),Or(Var 5,And(Var 5,Or(Not(Var 1),And(Not(Var 4),Or(Not(Var 0),And(Not(Var 3),Or(Var 2,And(Not(Var 5),Or(Var 4,And(Var 2,Or(Not(Var 3),And(Not(Var 1),Or(Not(Var 4),And(Not(Var 2),Or(Var 3,And(Not(Var 1),Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 5),And(Not(Var 1),Or(Var 1,And(Not(Var 4),Or(Not(Var 2),And(Var 5,Or(Var 1,And(Not(Var 2),Or(Var 5,And(Var 2,Or(Var 2,And(Not(Var 4),Or(Not(Var 2),And(Not(Var 3),Or(Var 5,And(Not(Var 5),Or(Var 5,And(Not(Var 3),Or(Not(Var 5),And(Not(Var 2),Or(Var 2,And(Not(Var 0),Or(Not(Var 4),And(Var 5,Or(Var 5,And(Var 0,Or(Not(Var 4),And(Var 3,Or(Not(Var 3),And(Var 3,Or(Not(Var 5),And(Not(Var 1),Or(Var 2,And(Var 1,Or(Var 4,And(Not(Var 1),Or(Not(Var 5),And(Not(Var 2),Or(Not(Var 2),And(Var 2,Or(Not(Var 3),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 0),And(Var 4,Or(Var 3,And(Not(Var 1),Or(Var 2,And(Var 5,Or(Var 5,And(Not(Var 2),Or(Var 5,And(Not(Var 4),Or(Not(Var 4),And(Var 0,Or(Not(Var 4),And(Var 2,Or(Not(Var 0),Not(Var 2))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 11),Or(Var 12,And(Var 21,Or(Not(Var 0),And(Var 18,Or(Var 6,And(Var 1,Or(Not(Var 24),And(Not(Var 6),Or(Not(Var 8),And(Not(Var 16),Or(Var 10,And(Not(Var 14),Or(Not(Var 24),And(Var 24,Or(Not(Var 24),And(Not(Var 14),Or(Var 17,And(Not(Var 25),Or(Var 6,And(Var 0,Or(Not(Var 0),And(Var 7,Or(Var 20,And(Var 2,Or(Not(Var 4),And(Var 6,Or(Not(Var 19),And(Var 10,Or(Var 4,And(Var 17,Or(Not(Var 19),And(Var 9,Or(Var 21,And(Not(Var 10),Or(Not(Var 10),And(Var 22,Or(Var 20,And(Not(Var 7),Or(Var 25,And(Var 4,Or(Var 12,And(Var 4,Or(Not(Var 22),And(Not(Var 23),Or(Not(Var 0),And(Not(Var 16),Or(Var 11,And(Not(Var 2),Or(Not(Var 0),And(Var 16,Or(Var 9,And(Not(Var 10),Or(Not(Var 12),And(Not(Var 11),Or(Not(Var 14),And(Var 18,Or(Var 14,And(Var 10,Or(Var 25,And(Var 18,Or(Var 25,And(Not(Var 23),Or(Not(Var 7),And(Var 17,Or(Var 8,And(Var 24,Or(Not(Var 23),And(Var 7,Or(Not(Var 15),And(Not(Var 26),Or(Not(Var 23),And(Var 4,Or(Not(Var 17),And(Var 10,Or(Var 11,And(Not(Var 14),Or(Not(Var 12),And(Not(Var 18),Or(Not(Var 23),And(Var 24,Or(Not(Var 18),And(Not(Var 1),Or(Not(Var 11),And(Not(Var 5),Not(Var 4)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 37,Or(Var 32,And(Var 19,Or(Not(Var 25),And(Var 7,Or(Var 3,And(Not(Var 40),Or(Var 4,And(Not(Var 23),Or(Var 23,And(Not(Var 30),Or(Var 14,And(Var 1,Or(Not(Var 28),And(Not(Var 21),Or(Not(Var 2),And(Var 35,Or(Not(Var 11),And(Var 40,Or(Not(Var 5),And(Var 39,Or(Not(Var 29),And(Not(Var 1),Or(Var 34,And(Var 28,Or(Not(Var 20),And(Var 34,Or(Not(Var 14),And(Not(Var 29),Or(Not(Var 13),And(Var 40,Or(Not(Var 16),And(Var 9,Or(Var 33,And(Var 26,Or(Not(Var 24),And(Var 4,Or(Var 27,And(Var 24,Or(Not(Var 3),And(Var 9,Or(Not(Var 31),And(Not(Var 23),Or(Not(Var 16),And(Not(Var 16),Or(Not(Var 23),And(Not(Var 2),Or(Var 26,And(Not(Var 35),Or(Not(Var 4),And(Var 23,Or(Var 23,And(Var 29,Or(Var 14,And(Var 14,Or(Var 18,And(Var 5,Or(Var 34,And(Var 5,Or(Var 6,And(Var 18,Or(Not(Var 9),And(Not(Var 6),Or(Not(Var 14),And(Var 20,Or(Var 35,And(Not(Var 21),Or(Var 3,And(Not(Var 3),Or(Not(Var 31),And(Var 5,Or(Var 36,And(Not(Var 7),Or(Not(Var 19),And(Var 35,Or(Var 23,And(Var 8,Or(Var 39,And(Not(Var 34),Or(Not(Var 17),And(Var 25,Or(Var 6,And(Not(Var 4),Or(Var 35,And(Not(Var 9),Or(Var 40,Var 40)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 10),Or(Not(Var 17),And(Var 16,Or(Not(Var 21),And(Var 19,Or(Not(Var 22),And(Var 21,Or(Not(Var 5),And(Var 6,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 2),And(Not(Var 10),Or(Not(Var 23),And(Not(Var 8),Or(Var 5,And(Var 13,Or(Var 17,And(Not(Var 18),Or(Not(Var 24),And(Not(Var 14),Or(Var 14,And(Var 9,Or(Var 11,And(Var 10,Or(Var 14,And(Not(Var 21),Or(Not(Var 21),And(Var 12,Or(Var 15,And(Not(Var 6),Or(Not(Var 4),And(Not(Var 21),Or(Var 4,And(Var 1,Or(Var 19,And(Not(Var 9),Or(Var 20,And(Not(Var 8),Or(Not(Var 18),And(Not(Var 18),Or(Var 19,And(Not(Var 18),Or(Not(Var 11),And(Not(Var 18),Or(Var 17,And(Var 13,Or(Not(Var 24),And(Var 5,Or(Var 11,And(Var 3,Or(Not(Var 21),And(Var 1,Or(Not(Var 8),And(Not(Var 1),Or(Not(Var 6),And(Var 11,Or(Not(Var 18),And(Var 8,Or(Not(Var 5),And(Var 9,Or(Var 4,And(Not(Var 0),Or(Not(Var 8),And(Var 2,Or(Not(Var 1),And(Var 23,Or(Var 8,And(Not(Var 12),Or(Not(Var 6),And(Not(Var 3),Or(Var 0,And(Not(Var 18),Or(Var 3,And(Var 12,Or(Var 0,And(Not(Var 16),Or(Not(Var 21),And(Var 21,Or(Not(Var 15),And(Not(Var 6),Or(Not(Var 17),And(Var 15,Or(Var 2,And(Not(Var 7),Or(Var 8,And(Var 23,Var 6))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 0,And(Var 2,Or(Var 1,And(Not(Var 5),Or(Not(Var 0),And(Not(Var 3),Or(Var 5,And(Var 1,Or(Var 3,And(Var 2,Or(Not(Var 2),And(Var 1,Or(Var 5,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 1),Or(Var 2,And(Not(Var 5),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 3),And(Not(Var 5),Or(Not(Var 3),And(Var 5,Or(Not(Var 5),And(Var 2,Or(Var 0,And(Not(Var 3),Or(Var 0,And(Not(Var 5),Or(Not(Var 4),And(Var 5,Or(Var 5,And(Var 0,Or(Var 2,And(Var 0,Or(Var 5,And(Var 1,Or(Var 3,And(Var 1,Or(Not(Var 5),And(Not(Var 5),Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 0),Or(Var 1,And(Var 2,Or(Var 1,And(Var 5,Or(Not(Var 5),And(Not(Var 4),Or(Not(Var 3),And(Var 4,Or(Var 0,And(Not(Var 1),Or(Var 0,And(Var 3,Or(Var 5,And(Var 2,Or(Not(Var 3),And(Var 2,Or(Var 5,And(Var 3,Or(Var 4,And(Not(Var 5),Or(Var 4,And(Var 3,Or(Var 4,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 4),Or(Var 2,And(Not(Var 2),Or(Var 4,And(Not(Var 2),Or(Not(Var 2),And(Var 1,Or(Var 5,And(Var 4,Or(Var 2,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 5),Or(Var 5,And(Not(Var 5),Or(Not(Var 4),Not(Var 1))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 2),Or(Not(Var 0),And(Var 0,Or(Not(Var 3),And(Var 2,Or(Not(Var 1),And(Var 2,Or(Not(Var 2),And(Not(Var 2),Or(Not(Var 1),And(Var 0,Or(Not(Var 3),And(Not(Var 1),Or(Var 0,And(Var 1,Or(Var 2,And(Var 0,Or(Var 2,And(Not(Var 2),Or(Not(Var 2),And(Not(Var 0),Or(Var 0,And(Not(Var 1),Or(Var 2,And(Not(Var 2),Or(Not(Var 0),And(Not(Var 2),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 3),Or(Var 3,And(Not(Var 2),Or(Not(Var 3),And(Var 1,Or(Not(Var 2),And(Not(Var 0),Or(Var 1,And(Var 1,Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 3),And(Var 2,Or(Var 0,And(Var 2,Or(Var 1,And(Not(Var 0),Or(Var 3,And(Var 3,Or(Not(Var 0),And(Var 3,Or(Var 1,And(Var 2,Or(Not(Var 0),And(Var 0,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Var 3,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 3),Or(Var 3,And(Not(Var 1),Or(Var 3,And(Var 3,Or(Var 1,And(Var 2,Or(Var 3,And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Var 2,And(Not(Var 1),Or(Not(Var 0),And(Var 3,Or(Not(Var 2),And(Var 3,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 3,Var 3))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Not(Var 13),And(Not(Var 6),Or(Var 3,And(Var 14,Or(Not(Var 12),And(Var 10,Or(Var 6,And(Not(Var 15),Or(Not(Var 9),And(Var 5,Or(Not(Var 18),And(Var 7,Or(Var 12,And(Not(Var 20),Or(Not(Var 9),And(Var 12,Or(Not(Var 23),And(Not(Var 12),Or(Var 15,And(Var 16,Or(Var 19,And(Var 9,Or(Var 21,And(Var 21,Or(Not(Var 18),And(Var 20,Or(Not(Var 7),And(Var 18,Or(Var 15,And(Var 10,Or(Var 14,And(Not(Var 14),Or(Var 21,And(Not(Var 5),Or(Not(Var 9),And(Var 21,Or(Not(Var 5),And(Not(Var 0),Or(Var 2,And(Not(Var 6),Or(Var 2,And(Var 19,Or(Var 10,And(Not(Var 10),Or(Var 20,And(Not(Var 5),Or(Var 21,And(Var 22,Or(Var 8,And(Var 10,Or(Var 21,And(Var 16,Or(Not(Var 3),And(Var 22,Or(Not(Var 10),And(Not(Var 1),Or(Not(Var 10),And(Not(Var 22),Or(Not(Var 13),And(Var 10,Or(Not(Var 12),And(Var 3,Or(Not(Var 17),And(Var 12,Or(Not(Var 19),And(Not(Var 4),Or(Not(Var 14),And(Not(Var 22),Or(Var 22,And(Not(Var 19),Or(Var 7,And(Var 12,Or(Var 0,And(Not(Var 21),Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 4),And(Var 19,Or(Not(Var 4),And(Var 5,Or(Var 9,And(Var 14,Or(Not(Var 10),And(Var 9,Or(Not(Var 22),And(Var 23,Or(Not(Var 12),And(Var 22,Or(Var 19,Var 1)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 4),And(Var 4,Or(Var 8,And(Not(Var 3),Or(Var 1,And(Not(Var 1),Or(Var 1,And(Not(Var 7),Or(Var 10,And(Var 7,Or(Var 2,And(Var 10,Or(Var 3,And(Var 8,Or(Var 1,And(Var 5,Or(Not(Var 1),And(Var 1,Or(Var 8,And(Var 7,Or(Not(Var 8),And(Not(Var 4),Or(Not(Var 2),And(Var 2,Or(Var 2,And(Var 8,Or(Not(Var 5),And(Not(Var 3),Or(Var 4,And(Not(Var 2),Or(Var 7,And(Var 10,Or(Var 0,And(Not(Var 4),Or(Var 5,And(Var 8,Or(Var 8,And(Var 4,Or(Var 9,And(Var 0,Or(Var 2,And(Var 0,Or(Var 7,And(Not(Var 0),Or(Var 6,And(Var 3,Or(Not(Var 1),And(Var 6,Or(Not(Var 8),And(Var 1,Or(Var 7,And(Not(Var 9),Or(Not(Var 8),And(Var 7,Or(Not(Var 1),And(Var 6,Or(Not(Var 6),And(Var 5,Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 10),And(Var 0,Or(Not(Var 1),And(Not(Var 9),Or(Var 1,And(Not(Var 5),Or(Var 7,And(Not(Var 7),Or(Var 1,And(Var 4,Or(Not(Var 2),And(Not(Var 9),Or(Not(Var 1),And(Not(Var 2),Or(Var 7,And(Var 1,Or(Not(Var 10),And(Var 5,Or(Var 5,And(Not(Var 7),Or(Var 9,And(Not(Var 10),Or(Var 2,And(Not(Var 10),Or(Var 5,And(Var 9,Or(Not(Var 3),And(Not(Var 4),Or(Not(Var 5),And(Var 8,Var 0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 4),Or(Var 5,And(Var 5,Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 3),And(Var 2,Or(Var 0,And(Var 4,Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 0),And(Var 4,Or(Not(Var 3),And(Var 0,Or(Not(Var 2),And(Var 1,Or(Var 1,And(Var 0,Or(Var 4,And(Var 2,Or(Var 4,And(Var 1,Or(Not(Var 0),And(Not(Var 3),Or(Var 5,And(Var 4,Or(Var 2,And(Not(Var 4),Or(Not(Var 3),And(Not(Var 2),Or(Var 2,And(Var 0,Or(Var 1,And(Not(Var 5),Or(Var 4,And(Var 1,Or(Not(Var 0),And(Not(Var 4),Or(Var 2,And(Not(Var 5),Or(Var 2,And(Not(Var 3),Or(Var 3,And(Var 3,Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Not(Var 1),Or(Var 2,And(Var 4,Or(Var 5,And(Not(Var 4),Or(Not(Var 4),And(Not(Var 1),Or(Var 0,And(Var 1,Or(Not(Var 4),And(Var 2,Or(Var 1,And(Var 1,Or(Var 3,And(Var 0,Or(Var 1,And(Not(Var 4),Or(Var 0,And(Var 2,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 2,Or(Not(Var 4),And(Not(Var 5),Or(Not(Var 4),And(Var 0,Or(Not(Var 3),And(Not(Var 0),Or(Var 2,And(Var 0,Or(Not(Var 2),And(Not(Var 5),Or(Var 4,And(Var 2,Or(Var 0,And(Not(Var 1),Or(Var 5,And(Var 5,Or(Not(Var 4),And(Var 3,Or(Not(Var 0),Not(Var 2))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 8,Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 9),And(Not(Var 9),Or(Not(Var 7),And(Not(Var 5),Or(Not(Var 2),And(Var 11,Or(Var 0,And(Not(Var 3),Or(Not(Var 6),And(Not(Var 8),Or(Var 2,And(Var 8,Or(Not(Var 9),And(Var 4,Or(Not(Var 9),And(Not(Var 6),Or(Not(Var 2),And(Not(Var 11),Or(Var 4,And(Var 1,Or(Var 9,And(Var 8,Or(Var 0,And(Var 6,Or(Var 2,And(Var 11,Or(Var 3,And(Var 8,Or(Not(Var 1),And(Var 3,Or(Not(Var 11),And(Not(Var 11),Or(Var 0,And(Var 6,Or(Var 9,And(Var 6,Or(Var 7,And(Var 9,Or(Var 2,And(Not(Var 9),Or(Var 8,And(Not(Var 3),Or(Not(Var 2),And(Var 9,Or(Not(Var 3),And(Var 10,Or(Not(Var 8),And(Not(Var 9),Or(Var 8,And(Not(Var 0),Or(Not(Var 7),And(Var 7,Or(Not(Var 8),And(Not(Var 0),Or(Not(Var 5),And(Not(Var 11),Or(Var 0,And(Not(Var 8),Or(Not(Var 11),And(Not(Var 4),Or(Not(Var 9),And(Var 4,Or(Var 10,And(Var 7,Or(Var 3,And(Not(Var 3),Or(Not(Var 6),And(Not(Var 1),Or(Not(Var 6),And(Var 1,Or(Var 7,And(Var 9,Or(Var 4,And(Var 2,Or(Var 10,And(Not(Var 8),Or(Var 9,And(Var 9,Or(Var 10,And(Not(Var 2),Or(Var 10,And(Var 4,Or(Not(Var 4),And(Not(Var 9),Or(Not(Var 1),And(Not(Var 10),Or(Var 6,And(Not(Var 7),Or(Not(Var 5),And(Not(Var 10),Not(Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Not(Var 0),And(Var 1,Or(Not(Var 0),And(Var 0,Or(Var 1,And(Not(Var 0),Or(Var 0,And(Not(Var 1),Or(Var 0,And(Var 1,Or(Var 0,And(Var 1,Or(Var 1,And(Not(Var 1),Or(Not(Var 1),And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 1,Or(Var 0,And(Not(Var 0),Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Var 1,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 0,And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 1,And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 1),Or(Var 0,And(Var 1,Or(Not(Var 0),And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 0,And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 1,And(Var 0,Or(Var 1,And(Not(Var 1),Or(Var 0,Var 0)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 18,And(Var 7,Or(Not(Var 1),And(Not(Var 18),Or(Not(Var 16),And(Not(Var 0),Or(Not(Var 14),And(Var 20,Or(Var 2,And(Var 16,Or(Not(Var 1),And(Var 2,Or(Not(Var 11),And(Not(Var 20),Or(Not(Var 3),And(Not(Var 20),Or(Var 8,And(Var 21,Or(Not(Var 3),And(Var 17,Or(Var 20,And(Var 4,Or(Var 6,And(Var 14,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 10),And(Not(Var 13),Or(Var 10,And(Var 16,Or(Not(Var 10),And(Var 7,Or(Not(Var 21),And(Not(Var 11),Or(Var 18,And(Not(Var 8),Or(Not(Var 13),And(Not(Var 10),Or(Not(Var 2),And(Var 15,Or(Not(Var 19),And(Var 14,Or(Var 8,And(Not(Var 4),Or(Not(Var 12),And(Var 6,Or(Var 16,And(Not(Var 19),Or(Var 4,And(Var 19,Or(Not(Var 13),And(Not(Var 5),Or(Not(Var 11),And(Var 20,Or(Var 14,And(Not(Var 18),Or(Var 10,And(Var 20,Or(Not(Var 8),And(Var 21,Or(Var 15,And(Not(Var 10),Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 13),And(Not(Var 6),Or(Not(Var 12),And(Not(Var 16),Or(Not(Var 11),And(Not(Var 13),Or(Var 17,And(Not(Var 9),Or(Var 21,And(Var 0,Or(Var 2,And(Not(Var 14),Or(Not(Var 4),And(Not(Var 16),Or(Not(Var 21),And(Var 7,Or(Var 7,And(Not(Var 2),Or(Var 4,And(Var 11,Or(Var 6,And(Var 11,Or(Var 8,And(Var 2,Or(Not(Var 11),And(Not(Var 9),Or(Not(Var 20),And(Not(Var 11),Or(Var 19,And(Var 2,Var 4))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),Not(Var 0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 7),Or(Not(Var 8),And(Not(Var 0),Or(Var 5,And(Not(Var 17),Or(Not(Var 9),And(Not(Var 5),Or(Not(Var 0),And(Var 16,Or(Var 7,And(Not(Var 9),Or(Not(Var 6),And(Var 16,Or(Not(Var 9),And(Var 15,Or(Var 20,And(Not(Var 0),Or(Not(Var 17),And(Not(Var 6),Or(Not(Var 15),And(Var 9,Or(Not(Var 18),And(Var 14,Or(Var 6,And(Var 21,Or(Not(Var 0),And(Not(Var 8),Or(Not(Var 18),And(Not(Var 13),Or(Var 1,And(Var 2,Or(Not(Var 9),And(Not(Var 2),Or(Var 12,And(Var 8,Or(Var 19,And(Not(Var 1),Or(Not(Var 21),And(Var 6,Or(Not(Var 21),And(Not(Var 10),Or(Not(Var 8),And(Not(Var 6),Or(Not(Var 3),And(Var 15,Or(Not(Var 8),And(Not(Var 2),Or(Not(Var 18),And(Var 13,Or(Var 12,And(Var 0,Or(Var 8,And(Var 17,Or(Var 4,And(Var 13,Or(Var 9,And(Var 1,Or(Not(Var 17),And(Not(Var 4),Or(Not(Var 20),And(Var 12,Or(Var 7,And(Not(Var 12),Or(Var 12,And(Var 16,Or(Var 3,And(Var 13,Or(Var 21,And(Not(Var 9),Or(Var 14,And(Var 14,Or(Not(Var 10),And(Not(Var 14),Or(Not(Var 7),And(Var 12,Or(Var 2,And(Var 9,Or(Not(Var 6),And(Not(Var 1),Or(Not(Var 11),And(Not(Var 13),Or(Var 2,And(Var 7,Or(Not(Var 11),And(Not(Var 14),Or(Not(Var 10),And(Var 22,Or(Var 11,And(Not(Var 8),Or(Var 18,And(Not(Var 12),Or(Not(Var 21),And(Not(Var 0),Or(Not(Var 15),And(Var 20,Or(Not(Var 19),And(Var 6,Var 6))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 12),Or(Var 1,And(Not(Var 6),Or(Var 11,And(Var 1,Or(Var 15,And(Var 7,Or(Not(Var 11),And(Var 4,Or(Not(Var 2),And(Var 5,Or(Not(Var 3),And(Not(Var 11),Or(Not(Var 7),And(Var 11,Or(Not(Var 9),And(Var 4,Or(Var 7,And(Not(Var 3),Or(Not(Var 6),And(Var 5,Or(Not(Var 12),And(Var 9,Or(Not(Var 5),And(Var 5,Or(Not(Var 2),And(Var 7,Or(Var 0,And(Not(Var 9),Or(Var 8,And(Not(Var 9),Or(Not(Var 8),And(Not(Var 13),Or(Var 1,And(Var 10,Or(Not(Var 9),And(Not(Var 15),Or(Var 9,And(Var 3,Or(Not(Var 2),And(Var 6,Or(Var 6,And(Not(Var 4),Or(Var 0,And(Var 3,Or(Not(Var 6),And(Not(Var 1),Or(Var 4,And(Not(Var 0),Or(Not(Var 15),And(Not(Var 11),Or(Not(Var 10),And(Var 3,Or(Var 15,And(Var 3,Or(Not(Var 12),And(Var 11,Or(Not(Var 5),And(Not(Var 12),Or(Not(Var 6),And(Var 10,Or(Not(Var 3),And(Var 14,Or(Not(Var 14),And(Not(Var 4),Or(Var 1,And(Not(Var 4),Or(Not(Var 1),And(Var 11,Or(Not(Var 2),And(Var 1,Or(Not(Var 10),And(Not(Var 15),Or(Not(Var 4),And(Var 2,Or(Var 12,And(Not(Var 12),Or(Var 6,And(Var 9,Or(Var 10,And(Not(Var 5),Or(Not(Var 7),And(Var 3,Or(Var 4,And(Not(Var 2),Or(Var 11,And(Var 11,Or(Var 6,And(Var 6,Or(Var 2,And(Not(Var 14),Or(Var 12,And(Not(Var 5),Or(Var 5,And(Not(Var 12),Or(Not(Var 0),And(Var 11,Or(Var 1,Var 10)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 11),Or(Not(Var 4),And(Not(Var 26),Or(Not(Var 22),And(Var 17,Or(Not(Var 13),And(Not(Var 2),Or(Var 19,And(Var 22,Or(Not(Var 10),And(Not(Var 18),Or(Var 15,And(Not(Var 3),Or(Var 12,And(Not(Var 15),Or(Not(Var 18),And(Var 10,Or(Not(Var 23),And(Not(Var 4),Or(Not(Var 25),And(Not(Var 11),Or(Var 3,And(Var 24,Or(Var 25,And(Not(Var 15),Or(Not(Var 17),And(Not(Var 23),Or(Not(Var 24),And(Not(Var 10),Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 22),And(Var 0,Or(Var 23,And(Not(Var 8),Or(Var 18,And(Var 4,Or(Not(Var 1),And(Var 18,Or(Not(Var 23),And(Var 21,Or(Not(Var 18),And(Not(Var 14),Or(Not(Var 9),And(Not(Var 26),Or(Var 19,And(Var 19,Or(Not(Var 7),And(Var 9,Or(Not(Var 6),And(Var 11,Or(Not(Var 10),And(Not(Var 4),Or(Not(Var 17),And(Not(Var 8),Or(Not(Var 18),And(Var 4,Or(Not(Var 17),And(Not(Var 9),Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 2),And(Var 2,Or(Not(Var 7),And(Var 15,Or(Not(Var 15),And(Var 13,Or(Var 24,And(Var 13,Or(Not(Var 6),And(Var 9,Or(Not(Var 8),And(Var 13,Or(Var 24,And(Not(Var 26),Or(Not(Var 10),And(Var 25,Or(Not(Var 1),And(Var 6,Or(Not(Var 2),And(Not(Var 10),Or(Not(Var 4),And(Not(Var 12),Or(Var 10,And(Not(Var 11),Or(Not(Var 21),And(Not(Var 21),Or(Not(Var 14),And(Var 3,Or(Var 18,And(Not(Var 16),Or(Var 23,And(Var 13,Or(Not(Var 8),And(Var 5,Or(Not(Var 21),And(Var 4,Or(Not(Var 6),And(Not(Var 9),Not(Var 19)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 22),And(Not(Var 3),Or(Var 8,And(Not(Var 26),Or(Not(Var 9),And(Var 12,Or(Not(Var 8),And(Var 6,Or(Not(Var 6),And(Not(Var 28),Or(Var 19,And(Var 27,Or(Var 13,And(Var 26,Or(Not(Var 26),And(Var 13,Or(Not(Var 11),And(Not(Var 18),Or(Not(Var 8),And(Var 20,Or(Not(Var 1),And(Var 25,Or(Not(Var 3),And(Var 3,Or(Var 3,And(Var 13,Or(Not(Var 1),And(Not(Var 16),Or(Not(Var 13),And(Not(Var 0),Or(Var 27,And(Var 23,Or(Var 2,And(Not(Var 3),Or(Var 8,And(Not(Var 6),Or(Not(Var 24),And(Var 16,Or(Var 16,And(Var 27,Or(Not(Var 7),And(Var 16,Or(Not(Var 11),And(Not(Var 8),Or(Not(Var 11),And(Var 14,Or(Var 9,And(Var 10,Or(Not(Var 0),And(Not(Var 7),Or(Var 17,And(Var 19,Or(Var 1,And(Not(Var 16),Or(Var 10,And(Var 25,Or(Not(Var 3),And(Var 5,Or(Var 9,And(Not(Var 27),Or(Var 21,And(Var 17,Or(Not(Var 14),And(Var 10,Or(Not(Var 11),And(Not(Var 28),Or(Var 10,And(Var 13,Or(Var 5,And(Not(Var 6),Or(Var 20,And(Var 4,Or(Not(Var 25),And(Var 20,Or(Not(Var 4),And(Not(Var 13),Or(Var 10,And(Not(Var 16),Or(Var 16,And(Not(Var 2),Or(Not(Var 25),And(Var 18,Or(Not(Var 4),And(Var 10,Or(Not(Var 14),And(Not(Var 5),Or(Not(Var 8),And(Var 20,Or(Not(Var 18),And(Var 9,Or(Not(Var 5),And(Var 27,Or(Not(Var 7),And(Not(Var 7),Or(Not(Var 5),And(Var 5,Or(Not(Var 12),And(Not(Var 26),Or(Var 18,Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
|]

let tests : unit =
  let t = Sys.time() in
  for i = 0 to Array.length formulas -1 do
    let _ = sat formulas.(i) in ()
  done;Printf.printf "Execution time (SAT): %fs\n" (Sys.time() -. t);;