type prop =
  | Var of int
  | Not of prop
  | And of prop * prop
  | Or  of prop * prop

(* Une branche c'est une liste de formule avec un signe *)
type branch =  (bool * prop) list

let is_literal = function
  | (true, Var _) -> true
  | (false, Var _) -> true
  | (true, Not (Var _)) -> true
  | (false, Not (Var _)) -> true
  | _ -> false

(* Check les contradictions *)
let branch_closed (br : branch) : bool =
  let pos = Hashtbl.create 16 in
  let neg = Hashtbl.create 16 in
  let record = function
    | (true, Var v) -> Hashtbl.replace pos v true
    | (false, Var v) -> Hashtbl.replace neg v true
    | (true, Not (Var v)) -> Hashtbl.replace neg v true
    | (false, Not (Var v)) -> Hashtbl.replace pos v true
    | _ -> ()
  in
  List.iter record br;
  let closed = ref false in
  Hashtbl.iter (fun v _ ->
    if (Hashtbl.mem pos v) && (Hashtbl.mem neg v) then closed := true
  ) pos;
  !closed

(* La decomposition usuelle faites durant la méthode des tableaux *)
let decompose_once (br : branch) : branch list option =
  let rec find_nonlit acc = function
    | [] -> None
    | x :: xs ->
      if is_literal x then find_nonlit (x::acc) xs
      else Some (List.rev acc, x, xs)
  in
  match find_nonlit [] br with
  | None -> None
  | Some (left, (sign, form), right) ->
    let rest = left @ right in
    let mk b p = (b, p) in
    (match sign, form with
     | true, And (a,b) ->
       Some [ (mk true a) :: (mk true b) :: rest ]
     | false, Or (a,b) ->
       Some [ (mk false a) :: (mk false b) :: rest ]
     | true, Or (a,b) ->
       Some [ (mk true a)::rest; (mk true b)::rest ]
     | false, And (a,b) ->
       Some [ (mk false a)::rest; (mk false b)::rest ]
     | true, Not a ->
       Some [ (mk false a) :: rest ]
     | false, Not a ->
       Some [ (mk true a) :: rest ]
     | _, _ -> None)

(* La Methode des Tableaux en soit *)
let satisfiable (phi : prop) : bool =
  let initial_branch = [ (true, phi) ] in
  let rec explore_stack stack =
    match stack with
    | [] -> false
    | br :: rest ->
      if branch_closed br then explore_stack rest else
      match decompose_once br with
      | None -> true
      | Some new_branches -> explore_stack (new_branches @ rest)
    in explore_stack [ initial_branch ]

let formulas = [|(And(Var 0,Var 0));
(And(Not(Var 0),Or(Not(Var 1),Not(Var 1))));
(And(Not(Var 0),Or(Var 1,And(Var 0,Var 1))));
(And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Not(Var 1),Not(Var 1))))));
(And(Var 2,Or(Not(Var 1),And(Var 0,Or(Var 2,And(Var 2,Var 1))))));
(And(Not(Var 0),Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,Var 0)))))));
(And(Not(Var 0),Or(Not(Var 2),And(Var 1,Or(Not(Var 2),And(Not(Var 3),Or(Var 2,And(Not(Var 1),Not(Var 2)))))))));
(And(Var 1,Or(Not(Var 4),And(Var 2,Or(Var 1,And(Var 0,Or(Not(Var 4),And(Var 2,Or(Not(Var 0),Not(Var 3))))))))));
(And(Not(Var 0),Or(Not(Var 0),And(Var 1,Or(Var 0,And(Var 2,Or(Not(Var 2),And(Not(Var 0),Or(Var 1,And(Not(Var 1),Not(Var 1)))))))))));
(And(Not(Var 2),Or(Not(Var 2),And(Var 1,Or(Var 1,And(Not(Var 2),Or(Not(Var 0),And(Var 2,Or(Not(Var 1),And(Var 1,Or(Var 1,Var 1)))))))))));
(And(Not(Var 4),Or(Var 1,And(Not(Var 3),Or(Not(Var 1),And(Var 3,Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 3),And(Var 2,Or(Var 1,And(Not(Var 0),Not(Var 3)))))))))))));
(And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),Not(Var 0))))))))))))));
(And(Not(Var 5),Or(Var 3,And(Not(Var 2),Or(Not(Var 0),And(Not(Var 3),Or(Var 1,And(Not(Var 5),Or(Not(Var 1),And(Not(Var 5),Or(Var 6,And(Not(Var 3),Or(Var 2,And(Not(Var 3),Not(Var 3)))))))))))))));
(And(Not(Var 1),Or(Var 2,And(Not(Var 1),Or(Var 2,And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Var 0,And(Not(Var 2),Or(Var 1,And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Var 1,Var 0)))))))))))))));
(And(Var 1,Or(Var 1,And(Not(Var 3),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 3),Or(Var 3,And(Var 2,Or(Var 1,And(Var 3,Or(Var 0,And(Var 2,Or(Not(Var 4),And(Var 4,Var 4))))))))))))))));
(And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),Not(Var 0))))))))))))))))));
(And(Var 2,Or(Var 2,And(Not(Var 2),Or(Var 3,And(Var 3,Or(Var 0,And(Var 0,Or(Var 2,And(Var 2,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 2),And(Not(Var 0),Or(Var 1,And(Var 1,Var 3))))))))))))))))));
(And(Var 1,Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Var 1,Or(Var 0,And(Var 1,Or(Var 1,And(Var 0,Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 1,Or(Var 1,And(Var 0,Or(Var 0,Var 1)))))))))))))))))));
(And(Var 3,Or(Not(Var 0),And(Var 4,Or(Var 0,And(Var 9,Or(Var 5,And(Var 5,Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 1),And(Not(Var 6),Or(Not(Var 2),And(Var 6,Or(Var 0,And(Var 2,Or(Not(Var 3),And(Var 9,Or(Var 1,And(Not(Var 1),Not(Var 0)))))))))))))))))))));
(And(Not(Var 7),Or(Var 7,And(Var 2,Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 6),And(Not(Var 2),Or(Not(Var 6),And(Var 1,Or(Var 2,And(Not(Var 2),Or(Var 7,And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 5),And(Not(Var 1),Or(Not(Var 6),And(Var 3,Or(Var 3,Var 6)))))))))))))))))))));
(And(Var 8,Or(Not(Var 2),And(Not(Var 1),Or(Var 2,And(Not(Var 4),Or(Not(Var 3),And(Not(Var 2),Or(Var 7,And(Not(Var 6),Or(Var 4,And(Not(Var 4),Or(Var 6,And(Not(Var 6),Or(Var 6,And(Not(Var 0),Or(Var 2,And(Var 10,Or(Var 9,And(Not(Var 1),Or(Var 5,And(Var 3,Var 5))))))))))))))))))))));
(And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),Not(Var 0))))))))))))))))))))))));
(And(Var 6,Or(Not(Var 2),And(Var 7,Or(Var 2,And(Not(Var 3),Or(Var 2,And(Not(Var 4),Or(Not(Var 7),And(Var 4,Or(Not(Var 7),And(Var 0,Or(Not(Var 7),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 5),Or(Var 0,And(Var 2,Or(Not(Var 4),And(Var 1,Or(Var 6,And(Var 6,Or(Var 7,And(Var 2,Var 1))))))))))))))))))))))));
(And(Not(Var 5),Or(Var 5,And(Var 5,Or(Not(Var 8),And(Not(Var 8),Or(Not(Var 6),And(Var 4,Or(Not(Var 1),And(Not(Var 5),Or(Var 8,And(Var 7,Or(Not(Var 11),And(Not(Var 11),Or(Var 2,And(Not(Var 1),Or(Var 0,And(Not(Var 2),Or(Not(Var 5),And(Not(Var 5),Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 10),And(Var 5,Or(Not(Var 7),Not(Var 11))))))))))))))))))))))))));
(And(Not(Var 4),Or(Not(Var 1),And(Not(Var 4),Or(Var 4,And(Var 2,Or(Not(Var 3),And(Var 2,Or(Not(Var 1),And(Not(Var 2),Or(Var 2,And(Var 2,Or(Var 4,And(Var 0,Or(Not(Var 2),And(Var 1,Or(Var 0,And(Not(Var 2),Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 3),And(Var 0,Or(Not(Var 0),And(Var 1,Or(Not(Var 2),And(Var 0,Var 4))))))))))))))))))))))))));
(And(Var 3,Or(Var 1,And(Var 2,Or(Not(Var 3),And(Var 3,Or(Not(Var 0),And(Not(Var 0),Or(Var 1,And(Var 2,Or(Not(Var 4),And(Not(Var 4),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 3),Or(Not(Var 5),And(Not(Var 3),Or(Var 4,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 2,And(Var 3,Or(Not(Var 1),And(Var 1,Or(Not(Var 2),Not(Var 4))))))))))))))))))))))))))));
(And(Var 7,Or(Not(Var 2),And(Var 5,Or(Not(Var 9),And(Not(Var 3),Or(Not(Var 12),And(Not(Var 3),Or(Not(Var 0),And(Not(Var 12),Or(Var 3,And(Var 3,Or(Not(Var 7),And(Var 6,Or(Var 5,And(Var 10,Or(Var 2,And(Not(Var 6),Or(Not(Var 5),And(Var 10,Or(Not(Var 5),And(Var 4,Or(Var 2,And(Not(Var 12),Or(Not(Var 10),And(Not(Var 4),Or(Not(Var 8),And(Var 6,Var 1))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 1,And(Var 1,Or(Not(Var 1),And(Var 1,Or(Var 1,And(Var 1,Or(Var 0,And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 1,Or(Var 0,And(Var 1,Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 0),Or(Not(Var 1),Not(Var 1))))))))))))))))))))))))))))));
(And(Var 6,Or(Not(Var 3),And(Not(Var 5),Or(Not(Var 10),And(Not(Var 2),Or(Var 3,And(Not(Var 4),Or(Var 4,And(Not(Var 10),Or(Var 8,And(Var 3,Or(Not(Var 0),And(Not(Var 0),Or(Var 1,And(Var 2,Or(Not(Var 9),And(Var 11,Or(Var 4,And(Not(Var 0),Or(Var 2,And(Var 2,Or(Not(Var 8),And(Not(Var 11),Or(Not(Var 3),And(Not(Var 7),Or(Var 12,And(Var 4,Or(Var 3,And(Not(Var 2),Not(Var 1)))))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 11,And(Var 6,Or(Not(Var 6),And(Var 12,Or(Not(Var 9),And(Not(Var 3),Or(Not(Var 11),And(Not(Var 8),Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 5,And(Not(Var 8),Or(Not(Var 7),And(Not(Var 10),Or(Var 11,And(Not(Var 11),Or(Not(Var 0),And(Not(Var 5),Or(Not(Var 8),And(Var 0,Or(Var 10,And(Var 8,Or(Not(Var 12),And(Var 6,Or(Var 10,And(Var 5,Or(Var 4,Var 10)))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 1,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 1),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 1,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Var 1,And(Var 0,Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Var 1,Var 0))))))))))))))))))))))))))))))));
(And(Not(Var 6),Or(Not(Var 3),And(Var 0,Or(Var 0,And(Not(Var 3),Or(Not(Var 2),And(Not(Var 4),Or(Var 2,And(Var 1,Or(Var 6,And(Var 3,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Var 0,And(Var 6,Or(Not(Var 4),And(Var 0,Or(Not(Var 3),And(Var 5,Or(Var 2,And(Var 0,Or(Not(Var 6),And(Var 1,Or(Not(Var 3),And(Not(Var 1),Or(Var 6,And(Var 6,Or(Not(Var 6),And(Not(Var 2),Or(Not(Var 4),Not(Var 2))))))))))))))))))))))))))))))))));
(And(Not(Var 4),Or(Var 2,And(Var 6,Or(Var 3,And(Var 8,Or(Not(Var 8),And(Var 10,Or(Var 6,And(Var 8,Or(Not(Var 3),And(Not(Var 10),Or(Var 9,And(Not(Var 5),Or(Not(Var 8),And(Var 6,Or(Var 4,And(Not(Var 5),Or(Var 8,And(Not(Var 11),Or(Not(Var 10),And(Not(Var 0),Or(Var 5,And(Var 2,Or(Var 4,And(Var 2,Or(Not(Var 9),And(Not(Var 5),Or(Not(Var 7),And(Not(Var 11),Or(Not(Var 5),And(Var 9,Or(Var 11,And(Not(Var 7),Not(Var 9)))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 1,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Var 1,Or(Not(Var 1),And(Not(Var 1),Or(Var 1,And(Var 0,Or(Var 1,And(Not(Var 0),Or(Var 0,And(Var 1,Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Var 0,And(Not(Var 1),Or(Var 1,And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 0,And(Not(Var 0),Or(Not(Var 1),Not(Var 0))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 6,And(Not(Var 3),Or(Not(Var 3),And(Var 2,Or(Var 0,And(Not(Var 4),Or(Var 6,And(Var 5,Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 1),And(Var 1,Or(Var 2,And(Not(Var 7),Or(Var 6,And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 6),Or(Not(Var 5),And(Var 1,Or(Var 1,And(Var 2,Or(Not(Var 2),And(Var 6,Or(Not(Var 5),And(Var 2,Or(Not(Var 6),And(Var 4,Or(Var 0,And(Var 5,Or(Var 3,And(Var 6,Var 2))))))))))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 11,And(Not(Var 7),Or(Not(Var 8),And(Not(Var 1),Or(Var 8,And(Not(Var 10),Or(Not(Var 3),And(Var 2,Or(Var 3,And(Var 3,Or(Var 6,And(Not(Var 10),Or(Var 11,And(Not(Var 6),Or(Var 2,And(Not(Var 1),Or(Not(Var 10),And(Not(Var 3),Or(Var 9,And(Var 1,Or(Not(Var 3),And(Var 8,Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 11),And(Var 3,Or(Var 8,And(Not(Var 7),Or(Not(Var 2),And(Not(Var 7),Or(Var 5,And(Not(Var 6),Or(Not(Var 7),And(Var 6,Or(Var 0,Var 1)))))))))))))))))))))))))))))))))))));
(And(Var 10,Or(Var 15,And(Var 0,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 1),And(Var 11,Or(Not(Var 11),And(Var 2,Or(Not(Var 1),And(Var 12,Or(Not(Var 1),And(Var 12,Or(Not(Var 6),And(Not(Var 1),Or(Var 13,And(Var 6,Or(Not(Var 9),And(Var 4,Or(Not(Var 13),And(Not(Var 9),Or(Not(Var 3),And(Var 7,Or(Not(Var 5),And(Not(Var 13),Or(Not(Var 5),And(Not(Var 1),Or(Not(Var 4),And(Var 3,Or(Var 8,And(Not(Var 8),Or(Not(Var 7),And(Not(Var 11),Or(Not(Var 7),And(Not(Var 10),Or(Not(Var 13),And(Var 0,Var 3))))))))))))))))))))))))))))))))))))));
(And(Var 4,Or(Not(Var 3),And(Not(Var 2),Or(Var 12,And(Var 7,Or(Var 12,And(Not(Var 5),Or(Var 3,And(Var 0,Or(Var 2,And(Var 4,Or(Not(Var 11),And(Var 10,Or(Var 3,And(Not(Var 1),Or(Var 10,And(Not(Var 7),Or(Var 4,And(Var 7,Or(Not(Var 6),And(Var 9,Or(Not(Var 3),And(Not(Var 12),Or(Not(Var 8),And(Not(Var 9),Or(Not(Var 5),And(Var 1,Or(Var 6,And(Not(Var 2),Or(Not(Var 12),And(Var 4,Or(Not(Var 11),And(Not(Var 11),Or(Not(Var 0),And(Var 5,Or(Var 6,And(Not(Var 8),Or(Var 12,Var 9)))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 2),And(Var 7,Or(Var 6,And(Not(Var 5),Or(Not(Var 0),And(Not(Var 1),Or(Var 4,And(Var 5,Or(Var 1,And(Var 3,Or(Var 0,And(Not(Var 7),Or(Not(Var 3),And(Not(Var 5),Or(Not(Var 4),And(Var 3,Or(Not(Var 3),And(Var 7,Or(Not(Var 5),And(Not(Var 0),Or(Not(Var 6),And(Not(Var 0),Or(Var 1,And(Var 4,Or(Not(Var 3),And(Not(Var 2),Or(Var 2,And(Var 7,Or(Var 4,And(Var 4,Or(Var 6,And(Not(Var 1),Or(Var 1,And(Not(Var 5),Or(Not(Var 7),And(Var 4,Or(Var 2,And(Not(Var 7),Not(Var 1)))))))))))))))))))))))))))))))))))))))));
(And(Var 4,Or(Var 4,And(Var 9,Or(Var 6,And(Var 10,Or(Not(Var 7),And(Not(Var 3),Or(Var 3,And(Var 12,Or(Not(Var 4),And(Var 1,Or(Not(Var 1),And(Not(Var 14),Or(Not(Var 3),And(Not(Var 0),Or(Var 11,And(Not(Var 9),Or(Var 12,And(Not(Var 1),Or(Not(Var 12),And(Var 12,Or(Not(Var 11),And(Not(Var 11),Or(Not(Var 10),And(Var 5,Or(Var 1,And(Var 7,Or(Var 10,And(Var 4,Or(Var 1,And(Var 12,Or(Var 4,And(Not(Var 12),Or(Var 7,And(Var 7,Or(Not(Var 3),And(Var 13,Or(Not(Var 4),And(Not(Var 3),Or(Var 0,Var 11)))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 17),Or(Not(Var 7),And(Var 14,Or(Var 5,And(Var 5,Or(Not(Var 11),And(Not(Var 4),Or(Not(Var 5),And(Not(Var 18),Or(Var 3,And(Var 3,Or(Not(Var 11),And(Var 5,Or(Var 9,And(Var 16,Or(Var 9,And(Not(Var 2),Or(Var 7,And(Var 3,Or(Var 16,And(Var 7,Or(Var 14,And(Not(Var 7),Or(Var 17,And(Var 10,Or(Not(Var 9),And(Var 1,Or(Var 12,And(Var 1,Or(Var 8,And(Var 3,Or(Var 11,And(Var 6,Or(Var 11,And(Var 11,Or(Var 17,And(Var 17,Or(Not(Var 18),And(Not(Var 14),Or(Var 7,And(Not(Var 8),Not(Var 1)))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Not(Var 1),And(Var 8,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 3),And(Var 7,Or(Var 5,And(Var 9,Or(Var 1,And(Var 6,Or(Var 15,And(Not(Var 6),Or(Var 3,And(Not(Var 12),Or(Not(Var 15),And(Var 8,Or(Var 3,And(Var 3,Or(Not(Var 14),And(Var 11,Or(Var 14,And(Var 3,Or(Not(Var 6),And(Not(Var 5),Or(Var 2,And(Not(Var 10),Or(Var 6,And(Not(Var 13),Or(Not(Var 10),And(Var 3,Or(Var 9,And(Not(Var 1),Or(Var 14,And(Not(Var 5),Or(Var 15,And(Var 4,Or(Not(Var 2),And(Not(Var 7),Or(Not(Var 5),And(Not(Var 13),Or(Not(Var 13),Not(Var 10))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 3,And(Var 10,Or(Var 4,And(Var 6,Or(Not(Var 0),And(Var 9,Or(Not(Var 5),And(Var 10,Or(Var 12,And(Not(Var 9),Or(Var 7,And(Not(Var 5),Or(Var 7,And(Var 9,Or(Var 0,And(Not(Var 2),Or(Var 2,And(Not(Var 11),Or(Not(Var 11),And(Var 0,Or(Var 10,And(Var 9,Or(Not(Var 0),And(Not(Var 4),Or(Not(Var 12),And(Var 8,Or(Not(Var 6),And(Not(Var 12),Or(Not(Var 4),And(Not(Var 4),Or(Not(Var 8),And(Var 9,Or(Not(Var 5),And(Not(Var 9),Or(Not(Var 8),And(Not(Var 1),Or(Var 12,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 9),Or(Var 8,And(Not(Var 2),Not(Var 2)))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 8,And(Not(Var 12),Or(Not(Var 16),And(Not(Var 14),Or(Var 14,And(Not(Var 10),Or(Var 8,And(Var 10,Or(Var 15,And(Not(Var 14),Or(Not(Var 6),And(Not(Var 4),Or(Var 8,And(Var 1,Or(Not(Var 14),And(Var 2,Or(Not(Var 0),And(Not(Var 12),Or(Not(Var 10),And(Var 3,Or(Var 11,And(Var 8,Or(Var 5,And(Not(Var 1),Or(Var 11,And(Var 4,Or(Var 6,And(Not(Var 3),Or(Not(Var 4),And(Var 3,Or(Not(Var 2),And(Var 9,Or(Not(Var 11),And(Not(Var 3),Or(Var 5,And(Var 9,Or(Var 5,And(Not(Var 10),Or(Not(Var 14),And(Not(Var 16),Or(Var 13,And(Not(Var 13),Or(Var 5,Var 2)))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 5),Or(Not(Var 13),And(Not(Var 9),Or(Not(Var 0),And(Var 13,Or(Not(Var 9),And(Var 12,Or(Not(Var 13),And(Not(Var 13),Or(Var 7,And(Not(Var 1),Or(Not(Var 1),And(Not(Var 2),Or(Var 12,And(Not(Var 3),Or(Var 4,And(Var 6,Or(Var 12,And(Var 9,Or(Not(Var 5),And(Var 12,Or(Var 12,And(Not(Var 5),Or(Var 13,And(Not(Var 0),Or(Not(Var 4),And(Var 8,Or(Var 3,And(Var 8,Or(Not(Var 1),And(Not(Var 6),Or(Not(Var 9),And(Not(Var 1),Or(Var 5,And(Not(Var 10),Or(Not(Var 10),And(Not(Var 11),Or(Var 5,And(Var 8,Or(Var 7,And(Not(Var 8),Or(Not(Var 6),And(Var 12,Or(Not(Var 11),And(Var 13,Var 0))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Var 13,And(Not(Var 15),Or(Var 9,And(Var 11,Or(Var 13,And(Var 0,Or(Not(Var 9),And(Var 8,Or(Not(Var 4),And(Not(Var 17),Or(Var 0,And(Not(Var 14),Or(Var 4,And(Var 3,Or(Var 1,And(Not(Var 17),Or(Not(Var 9),And(Var 10,Or(Not(Var 9),And(Not(Var 7),Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 11),And(Not(Var 9),Or(Not(Var 14),And(Var 3,Or(Var 4,And(Not(Var 17),Or(Var 11,And(Not(Var 7),Or(Not(Var 16),And(Var 7,Or(Var 13,And(Var 6,Or(Var 11,And(Var 6,Or(Var 16,And(Var 9,Or(Not(Var 12),And(Var 1,Or(Var 5,And(Var 3,Or(Not(Var 0),And(Not(Var 12),Or(Var 3,Var 17)))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Var 2,And(Var 1,Or(Not(Var 3),And(Var 3,Or(Not(Var 4),And(Var 2,Or(Not(Var 2),And(Var 2,Or(Not(Var 4),And(Var 2,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 2),Or(Var 4,And(Not(Var 2),Or(Not(Var 1),And(Var 3,Or(Not(Var 3),And(Var 0,Or(Var 4,And(Var 1,Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 4),Or(Var 2,And(Not(Var 1),Or(Not(Var 2),And(Var 0,Or(Var 2,And(Not(Var 2),Or(Not(Var 2),And(Not(Var 0),Or(Var 3,And(Not(Var 3),Or(Var 4,And(Not(Var 1),Or(Var 4,And(Not(Var 3),Or(Var 0,And(Var 2,Or(Not(Var 0),And(Var 3,Or(Var 1,And(Var 0,Var 0))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 1,And(Not(Var 11),Or(Not(Var 13),And(Not(Var 8),Or(Var 0,And(Var 13,Or(Var 13,And(Not(Var 4),Or(Not(Var 7),And(Var 12,Or(Var 1,And(Var 12,Or(Not(Var 4),And(Var 8,Or(Var 5,And(Not(Var 6),Or(Var 11,And(Not(Var 4),Or(Not(Var 6),And(Var 10,Or(Not(Var 1),And(Not(Var 5),Or(Var 10,And(Var 10,Or(Not(Var 6),And(Not(Var 8),Or(Var 12,And(Not(Var 11),Or(Not(Var 1),And(Var 7,Or(Not(Var 11),And(Var 3,Or(Var 10,And(Not(Var 5),Or(Not(Var 3),And(Var 8,Or(Var 7,And(Not(Var 10),Or(Not(Var 10),And(Var 7,Or(Var 11,And(Var 8,Or(Not(Var 12),And(Not(Var 6),Or(Not(Var 13),And(Var 9,Or(Not(Var 3),Not(Var 8))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 3,Or(Not(Var 2),And(Var 6,Or(Not(Var 6),And(Var 6,Or(Not(Var 2),And(Not(Var 3),Or(Var 0,And(Not(Var 1),Or(Var 1,And(Not(Var 1),Or(Not(Var 2),And(Var 3,Or(Not(Var 5),And(Var 1,Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 1),And(Var 0,Or(Var 5,And(Not(Var 4),Or(Not(Var 6),And(Var 1,Or(Var 2,And(Var 5,Or(Not(Var 2),And(Var 7,Or(Not(Var 6),And(Not(Var 3),Or(Var 3,And(Not(Var 4),Or(Var 4,And(Var 4,Or(Not(Var 5),And(Var 2,Or(Var 0,And(Var 1,Or(Var 5,And(Var 5,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 3),And(Not(Var 7),Or(Var 2,And(Var 6,Or(Var 6,And(Var 0,Or(Not(Var 4),And(Var 6,Var 3))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 12),Or(Not(Var 7),And(Not(Var 9),Or(Not(Var 16),And(Not(Var 8),Or(Var 1,And(Var 15,Or(Not(Var 18),And(Not(Var 10),Or(Not(Var 5),And(Not(Var 19),Or(Not(Var 19),And(Var 0,Or(Var 2,And(Not(Var 17),Or(Not(Var 15),And(Not(Var 12),Or(Var 10,And(Var 4,Or(Var 9,And(Var 0,Or(Var 9,And(Not(Var 16),Or(Not(Var 10),And(Var 5,Or(Var 10,And(Not(Var 16),Or(Not(Var 11),And(Not(Var 11),Or(Var 12,And(Var 15,Or(Not(Var 18),And(Not(Var 17),Or(Not(Var 11),And(Not(Var 9),Or(Var 17,And(Not(Var 7),Or(Var 12,And(Not(Var 2),Or(Var 0,And(Not(Var 3),Or(Not(Var 17),And(Var 5,Or(Not(Var 13),And(Var 7,Or(Not(Var 15),And(Var 4,Or(Not(Var 12),And(Not(Var 14),Or(Var 11,Var 8)))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 5),Or(Var 9,And(Not(Var 2),Or(Not(Var 1),And(Not(Var 10),Or(Not(Var 7),And(Not(Var 8),Or(Not(Var 0),And(Var 6,Or(Not(Var 3),And(Var 6,Or(Var 9,And(Not(Var 6),Or(Var 3,And(Var 3,Or(Not(Var 6),And(Not(Var 4),Or(Not(Var 5),And(Var 3,Or(Not(Var 8),And(Not(Var 7),Or(Var 10,And(Not(Var 7),Or(Not(Var 3),And(Var 10,Or(Var 9,And(Var 4,Or(Not(Var 0),And(Var 10,Or(Not(Var 6),And(Var 0,Or(Var 7,And(Not(Var 7),Or(Var 0,And(Not(Var 7),Or(Var 0,And(Not(Var 9),Or(Not(Var 8),And(Var 4,Or(Var 10,And(Var 10,Or(Not(Var 8),And(Var 3,Or(Not(Var 1),And(Var 5,Or(Var 10,And(Not(Var 9),Or(Not(Var 2),And(Not(Var 7),Or(Not(Var 2),And(Var 1,Var 5))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 4),And(Var 2,Or(Not(Var 1),And(Not(Var 4),Or(Var 3,And(Var 3,Or(Var 1,And(Not(Var 1),Or(Var 4,And(Var 4,Or(Not(Var 0),And(Var 3,Or(Var 4,And(Not(Var 1),Or(Not(Var 2),And(Not(Var 0),Or(Var 0,And(Var 2,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 4),And(Var 4,Or(Var 0,And(Var 2,Or(Not(Var 1),And(Not(Var 4),Or(Var 1,And(Var 0,Or(Not(Var 0),And(Not(Var 2),Or(Var 2,And(Var 0,Or(Not(Var 3),And(Not(Var 2),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 3,Or(Not(Var 4),And(Var 2,Or(Var 4,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 4),Or(Not(Var 3),And(Var 3,Or(Not(Var 2),Not(Var 4))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 10),Or(Var 12,And(Var 8,Or(Var 6,And(Not(Var 7),Or(Var 11,And(Var 3,Or(Var 0,And(Var 11,Or(Not(Var 1),And(Var 13,Or(Not(Var 13),And(Var 3,Or(Not(Var 7),And(Not(Var 3),Or(Not(Var 4),And(Var 0,Or(Var 7,And(Var 7,Or(Not(Var 8),And(Not(Var 10),Or(Not(Var 1),And(Var 12,Or(Not(Var 4),And(Not(Var 7),Or(Not(Var 2),And(Var 13,Or(Not(Var 2),And(Not(Var 10),Or(Not(Var 9),And(Var 12,Or(Var 5,And(Not(Var 12),Or(Not(Var 11),And(Var 7,Or(Var 4,And(Var 2,Or(Not(Var 4),And(Var 8,Or(Var 10,And(Not(Var 13),Or(Not(Var 7),And(Not(Var 6),Or(Var 4,And(Var 3,Or(Not(Var 8),And(Var 6,Or(Var 9,And(Not(Var 13),Or(Not(Var 1),And(Not(Var 7),Or(Var 2,And(Var 11,Var 5))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Not(Var 5),And(Var 6,Or(Var 6,And(Not(Var 0),Or(Not(Var 3),And(Var 2,Or(Not(Var 1),And(Var 6,Or(Var 4,And(Not(Var 1),Or(Var 0,And(Not(Var 4),Or(Not(Var 5),And(Not(Var 4),Or(Not(Var 2),And(Not(Var 6),Or(Not(Var 6),And(Var 3,Or(Not(Var 2),And(Var 1,Or(Var 4,And(Var 4,Or(Not(Var 1),And(Not(Var 2),Or(Not(Var 3),And(Var 2,Or(Var 2,And(Not(Var 1),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 5),Or(Not(Var 2),And(Not(Var 1),Or(Var 0,And(Not(Var 0),Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 3),And(Not(Var 2),Or(Var 2,And(Var 4,Or(Var 0,And(Not(Var 1),Or(Var 2,And(Var 1,Or(Not(Var 6),And(Not(Var 6),Or(Var 6,And(Var 0,Or(Var 3,And(Not(Var 6),Or(Var 0,Var 1)))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 15,Or(Var 1,And(Var 18,Or(Not(Var 10),And(Not(Var 16),Or(Var 2,And(Not(Var 19),Or(Not(Var 0),And(Not(Var 9),Or(Not(Var 12),And(Var 17,Or(Not(Var 12),And(Not(Var 6),Or(Var 10,And(Var 2,Or(Not(Var 13),And(Not(Var 1),Or(Var 12,And(Var 1,Or(Var 14,And(Var 9,Or(Var 11,And(Var 7,Or(Var 19,And(Not(Var 15),Or(Not(Var 1),And(Not(Var 5),Or(Not(Var 6),And(Var 4,Or(Not(Var 10),And(Not(Var 19),Or(Var 17,And(Not(Var 5),Or(Not(Var 7),And(Var 17,Or(Var 18,And(Var 19,Or(Not(Var 6),And(Var 5,Or(Not(Var 9),And(Var 5,Or(Not(Var 10),And(Var 1,Or(Var 2,And(Not(Var 10),Or(Not(Var 5),And(Not(Var 1),Or(Not(Var 2),And(Var 4,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 2),And(Not(Var 17),Or(Not(Var 0),And(Var 5,Var 17))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 6),Or(Not(Var 17),And(Not(Var 5),Or(Not(Var 17),And(Var 0,Or(Var 3,And(Not(Var 8),Or(Not(Var 15),And(Var 13,Or(Var 11,And(Var 10,Or(Not(Var 4),And(Var 16,Or(Not(Var 10),And(Not(Var 19),Or(Var 1,And(Var 5,Or(Var 1,And(Not(Var 13),Or(Not(Var 19),And(Not(Var 13),Or(Not(Var 5),And(Var 2,Or(Not(Var 19),And(Var 10,Or(Not(Var 5),And(Not(Var 18),Or(Var 14,And(Var 19,Or(Not(Var 4),And(Var 20,Or(Not(Var 9),And(Not(Var 15),Or(Not(Var 7),And(Var 3,Or(Not(Var 15),And(Not(Var 16),Or(Var 12,And(Var 6,Or(Not(Var 12),And(Var 9,Or(Var 10,And(Var 1,Or(Var 20,And(Var 13,Or(Var 8,And(Var 9,Or(Var 10,And(Var 4,Or(Var 12,And(Var 16,Or(Var 17,And(Var 15,Or(Not(Var 8),And(Not(Var 5),Or(Not(Var 8),Not(Var 3))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 6,Or(Not(Var 8),And(Var 19,Or(Not(Var 12),And(Not(Var 12),Or(Var 10,And(Var 21,Or(Not(Var 0),And(Not(Var 20),Or(Var 5,And(Not(Var 10),Or(Var 21,And(Var 3,Or(Var 3,And(Var 1,Or(Not(Var 17),And(Var 13,Or(Not(Var 24),And(Not(Var 6),Or(Not(Var 4),And(Var 14,Or(Not(Var 24),And(Var 14,Or(Var 18,And(Not(Var 6),Or(Not(Var 14),And(Var 2,Or(Var 19,And(Not(Var 7),Or(Not(Var 0),And(Var 5,Or(Var 11,And(Var 9,Or(Var 5,And(Not(Var 18),Or(Var 5,And(Not(Var 13),Or(Not(Var 4),And(Var 14,Or(Var 11,And(Var 15,Or(Not(Var 14),And(Not(Var 22),Or(Var 11,And(Not(Var 20),Or(Not(Var 11),And(Var 24,Or(Not(Var 13),And(Not(Var 23),Or(Var 20,And(Not(Var 4),Or(Not(Var 22),And(Var 2,Or(Var 18,And(Not(Var 5),Or(Not(Var 16),And(Not(Var 11),Not(Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 12),Or(Not(Var 12),And(Not(Var 0),Or(Not(Var 12),And(Var 14,Or(Var 6,And(Var 12,Or(Var 4,And(Not(Var 16),Or(Not(Var 16),And(Var 8,Or(Not(Var 16),And(Not(Var 17),Or(Var 8,And(Not(Var 13),Or(Var 10,And(Var 4,Or(Not(Var 4),And(Not(Var 6),Or(Var 1,And(Not(Var 10),Or(Var 12,And(Not(Var 1),Or(Not(Var 15),And(Var 11,Or(Var 15,And(Var 13,Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 7),And(Not(Var 10),Or(Not(Var 14),And(Not(Var 8),Or(Var 11,And(Not(Var 13),Or(Var 15,And(Not(Var 2),Or(Not(Var 1),And(Var 6,Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 11),And(Not(Var 15),Or(Not(Var 6),And(Not(Var 5),Or(Var 14,And(Not(Var 10),Or(Var 1,And(Not(Var 18),Or(Not(Var 14),And(Var 1,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 0),And(Var 8,Or(Var 2,And(Not(Var 8),Or(Not(Var 4),Not(Var 10))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Var 19,And(Not(Var 22),Or(Var 10,And(Not(Var 2),Or(Var 17,And(Var 16,Or(Var 13,And(Var 6,Or(Var 14,And(Not(Var 2),Or(Var 9,And(Not(Var 6),Or(Not(Var 10),And(Var 22,Or(Not(Var 11),And(Var 15,Or(Not(Var 6),And(Var 14,Or(Not(Var 22),And(Var 9,Or(Var 9,And(Not(Var 18),Or(Var 17,And(Not(Var 11),Or(Not(Var 13),And(Var 12,Or(Var 12,And(Not(Var 8),Or(Not(Var 4),And(Not(Var 16),Or(Var 22,And(Var 2,Or(Var 12,And(Not(Var 1),Or(Not(Var 13),And(Not(Var 1),Or(Var 12,And(Not(Var 10),Or(Not(Var 7),And(Not(Var 20),Or(Not(Var 8),And(Var 0,Or(Var 17,And(Var 19,Or(Var 9,And(Not(Var 9),Or(Not(Var 16),And(Not(Var 3),Or(Not(Var 11),And(Var 1,Or(Not(Var 18),And(Var 17,Or(Var 3,And(Var 2,Or(Not(Var 9),And(Not(Var 7),Or(Not(Var 13),And(Var 0,Var 16))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 8,Or(Var 3,And(Var 7,Or(Not(Var 5),And(Var 11,Or(Not(Var 4),And(Var 10,Or(Var 12,And(Not(Var 6),Or(Var 2,And(Var 5,Or(Not(Var 5),And(Not(Var 13),Or(Var 1,And(Not(Var 10),Or(Var 1,And(Not(Var 12),Or(Not(Var 11),And(Not(Var 9),Or(Var 10,And(Var 5,Or(Var 7,And(Not(Var 12),Or(Var 13,And(Not(Var 2),Or(Not(Var 4),And(Not(Var 6),Or(Var 4,And(Not(Var 2),Or(Var 7,And(Not(Var 1),Or(Not(Var 12),And(Var 10,Or(Var 13,And(Not(Var 1),Or(Var 5,And(Var 1,Or(Not(Var 4),And(Var 7,Or(Var 5,And(Not(Var 11),Or(Not(Var 0),And(Not(Var 7),Or(Var 1,And(Not(Var 6),Or(Not(Var 11),And(Var 10,Or(Not(Var 6),And(Var 1,Or(Not(Var 5),And(Var 11,Or(Var 5,And(Var 9,Or(Not(Var 0),And(Not(Var 1),Or(Var 4,And(Not(Var 5),Or(Var 1,And(Not(Var 13),Or(Var 12,Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 9,Or(Not(Var 24),And(Var 1,Or(Var 20,And(Var 9,Or(Var 11,And(Not(Var 21),Or(Var 7,And(Not(Var 11),Or(Not(Var 7),And(Not(Var 14),Or(Not(Var 6),And(Not(Var 14),Or(Var 24,And(Var 2,Or(Var 5,And(Var 22,Or(Not(Var 12),And(Not(Var 17),Or(Var 9,And(Var 25,Or(Not(Var 14),And(Var 15,Or(Var 12,And(Var 24,Or(Var 13,And(Var 20,Or(Not(Var 13),And(Not(Var 9),Or(Var 0,And(Var 12,Or(Var 3,And(Var 2,Or(Var 18,And(Var 6,Or(Not(Var 12),And(Var 4,Or(Var 14,And(Var 7,Or(Not(Var 15),And(Not(Var 10),Or(Not(Var 4),And(Not(Var 23),Or(Not(Var 2),And(Not(Var 21),Or(Not(Var 19),And(Var 6,Or(Not(Var 9),And(Var 17,Or(Var 1,And(Not(Var 19),Or(Not(Var 14),And(Var 16,Or(Var 15,And(Not(Var 8),Or(Not(Var 16),And(Var 14,Or(Not(Var 8),And(Not(Var 2),Or(Not(Var 8),And(Var 2,Var 15))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 3),Or(Not(Var 4),And(Var 4,Or(Not(Var 1),And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 5),And(Not(Var 2),Or(Var 1,And(Var 4,Or(Var 3,And(Var 5,Or(Var 4,And(Var 2,Or(Not(Var 2),And(Not(Var 0),Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 5),And(Not(Var 2),Or(Var 3,And(Var 5,Or(Not(Var 0),And(Var 5,Or(Var 5,And(Var 4,Or(Not(Var 1),And(Var 1,Or(Not(Var 5),And(Var 3,Or(Var 2,And(Var 2,Or(Not(Var 0),And(Var 3,Or(Var 3,And(Not(Var 0),Or(Not(Var 3),And(Not(Var 2),Or(Var 4,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 0),Or(Var 4,And(Not(Var 2),Or(Var 4,And(Not(Var 1),Or(Not(Var 0),And(Var 3,Or(Var 1,And(Var 4,Or(Not(Var 2),And(Var 5,Or(Var 5,And(Var 4,Or(Not(Var 2),And(Not(Var 2),Or(Var 4,And(Var 4,Or(Var 0,And(Var 4,Or(Var 0,Var 2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 8,Or(Not(Var 11),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 2),Or(Not(Var 9),And(Var 12,Or(Var 0,And(Var 1,Or(Not(Var 0),And(Var 8,Or(Not(Var 3),And(Not(Var 6),Or(Var 12,And(Not(Var 3),Or(Not(Var 8),And(Not(Var 9),Or(Not(Var 10),And(Not(Var 4),Or(Var 1,And(Var 1,Or(Var 13,And(Not(Var 10),Or(Not(Var 13),And(Not(Var 13),Or(Var 3,And(Var 7,Or(Not(Var 13),And(Var 7,Or(Var 4,And(Not(Var 6),Or(Not(Var 12),And(Var 6,Or(Var 11,And(Var 15,Or(Not(Var 4),And(Var 5,Or(Var 7,And(Not(Var 1),Or(Var 2,And(Not(Var 9),Or(Not(Var 14),And(Not(Var 13),Or(Not(Var 5),And(Not(Var 5),Or(Not(Var 0),And(Not(Var 10),Or(Not(Var 12),And(Not(Var 8),Or(Var 7,And(Not(Var 4),Or(Not(Var 10),And(Not(Var 0),Or(Not(Var 9),And(Not(Var 12),Or(Not(Var 5),And(Not(Var 5),Or(Var 1,And(Var 4,Or(Not(Var 10),And(Var 4,Or(Not(Var 1),And(Not(Var 5),Not(Var 11)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 11),And(Not(Var 13),Or(Var 13,And(Var 5,Or(Not(Var 2),And(Var 26,Or(Var 22,And(Var 19,Or(Not(Var 4),And(Var 0,Or(Var 15,And(Var 18,Or(Not(Var 23),And(Not(Var 12),Or(Var 0,And(Var 5,Or(Var 3,And(Var 18,Or(Not(Var 2),And(Not(Var 9),Or(Var 23,And(Not(Var 9),Or(Not(Var 3),And(Not(Var 26),Or(Not(Var 8),And(Var 9,Or(Not(Var 9),And(Not(Var 17),Or(Not(Var 16),And(Var 6,Or(Not(Var 5),And(Not(Var 12),Or(Var 12,And(Not(Var 13),Or(Not(Var 23),And(Var 11,Or(Not(Var 16),And(Var 10,Or(Not(Var 14),And(Not(Var 5),Or(Not(Var 19),And(Var 15,Or(Var 9,And(Not(Var 13),Or(Var 5,And(Not(Var 11),Or(Not(Var 6),And(Not(Var 19),Or(Var 0,And(Var 7,Or(Var 12,And(Var 8,Or(Not(Var 16),And(Var 23,Or(Var 0,And(Not(Var 17),Or(Not(Var 12),And(Var 9,Or(Var 20,And(Var 14,Or(Var 5,Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 3,Or(Not(Var 6),And(Not(Var 5),Or(Var 17,And(Var 13,Or(Not(Var 15),And(Var 6,Or(Var 2,And(Var 9,Or(Var 8,And(Var 13,Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 3),And(Not(Var 12),Or(Not(Var 15),And(Not(Var 9),Or(Var 4,And(Var 4,Or(Var 3,And(Not(Var 4),Or(Var 11,And(Var 18,Or(Not(Var 14),And(Var 9,Or(Var 0,And(Var 2,Or(Var 5,And(Var 0,Or(Not(Var 12),And(Not(Var 8),Or(Not(Var 1),And(Not(Var 2),Or(Not(Var 9),And(Not(Var 14),Or(Var 3,And(Not(Var 6),Or(Var 14,And(Not(Var 17),Or(Not(Var 13),And(Var 18,Or(Var 0,And(Not(Var 18),Or(Not(Var 9),And(Not(Var 0),Or(Var 11,And(Not(Var 0),Or(Var 14,And(Var 7,Or(Var 18,And(Not(Var 1),Or(Not(Var 14),And(Var 1,Or(Var 1,And(Var 12,Or(Not(Var 5),And(Var 11,Or(Var 2,And(Var 10,Or(Not(Var 9),And(Var 5,Or(Var 9,And(Not(Var 14),Or(Var 7,And(Not(Var 0),Not(Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 2),Or(Not(Var 14),And(Not(Var 8),Or(Var 13,And(Var 10,Or(Var 5,And(Not(Var 5),Or(Var 1,And(Var 10,Or(Not(Var 1),And(Var 1,Or(Var 13,And(Var 0,Or(Not(Var 4),And(Var 10,Or(Not(Var 0),And(Not(Var 3),Or(Var 8,And(Var 7,Or(Var 12,And(Not(Var 13),Or(Not(Var 3),And(Not(Var 3),Or(Var 0,And(Var 11,Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Var 5,Or(Not(Var 12),And(Not(Var 12),Or(Var 1,And(Var 11,Or(Not(Var 8),And(Var 13,Or(Not(Var 12),And(Not(Var 5),Or(Var 12,And(Not(Var 7),Or(Not(Var 5),And(Var 0,Or(Var 1,And(Not(Var 9),Or(Var 4,And(Not(Var 1),Or(Not(Var 6),And(Var 10,Or(Not(Var 5),And(Var 1,Or(Not(Var 9),And(Var 0,Or(Var 2,And(Not(Var 9),Or(Var 0,And(Var 1,Or(Var 13,And(Var 2,Or(Var 2,And(Not(Var 13),Or(Not(Var 13),And(Var 14,Or(Not(Var 11),And(Var 10,Or(Var 9,And(Var 0,Or(Var 7,Var 10)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 27),Or(Var 13,And(Not(Var 3),Or(Var 26,And(Var 29,Or(Not(Var 0),And(Var 14,Or(Not(Var 6),And(Not(Var 12),Or(Not(Var 23),And(Not(Var 13),Or(Var 5,And(Var 23,Or(Var 8,And(Var 10,Or(Var 18,And(Var 6,Or(Var 8,And(Not(Var 1),Or(Var 27,And(Not(Var 21),Or(Var 18,And(Not(Var 17),Or(Not(Var 23),And(Var 8,Or(Var 15,And(Not(Var 6),Or(Not(Var 6),And(Not(Var 28),Or(Not(Var 5),And(Not(Var 5),Or(Var 11,And(Var 22,Or(Not(Var 1),And(Var 17,Or(Var 2,And(Not(Var 19),Or(Var 31,And(Var 7,Or(Not(Var 20),And(Var 16,Or(Not(Var 10),And(Var 29,Or(Not(Var 8),And(Var 15,Or(Var 12,And(Var 19,Or(Not(Var 20),And(Not(Var 12),Or(Var 19,And(Not(Var 0),Or(Var 29,And(Not(Var 28),Or(Not(Var 13),And(Var 6,Or(Not(Var 29),And(Var 22,Or(Var 4,And(Not(Var 0),Or(Not(Var 19),And(Not(Var 32),Or(Var 19,And(Var 13,Or(Var 1,And(Not(Var 5),Or(Var 6,And(Var 25,Var 14))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 11),Or(Var 4,And(Not(Var 9),Or(Var 7,And(Var 0,Or(Var 5,And(Not(Var 4),Or(Var 2,And(Var 4,Or(Var 2,And(Not(Var 10),Or(Not(Var 2),And(Not(Var 7),Or(Var 0,And(Not(Var 3),Or(Not(Var 6),And(Not(Var 1),Or(Var 10,And(Var 1,Or(Var 9,And(Not(Var 9),Or(Var 8,And(Var 10,Or(Not(Var 1),And(Var 9,Or(Not(Var 5),And(Not(Var 8),Or(Not(Var 4),And(Var 5,Or(Not(Var 5),And(Var 9,Or(Not(Var 0),And(Var 11,Or(Var 0,And(Not(Var 5),Or(Var 10,And(Var 6,Or(Not(Var 6),And(Not(Var 4),Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 9),And(Not(Var 10),Or(Not(Var 11),And(Var 4,Or(Not(Var 0),And(Var 8,Or(Var 4,And(Not(Var 2),Or(Not(Var 9),And(Not(Var 0),Or(Var 11,And(Var 1,Or(Var 8,And(Not(Var 0),Or(Var 4,And(Not(Var 7),Or(Var 3,And(Not(Var 4),Or(Not(Var 0),And(Var 0,Or(Var 2,And(Not(Var 9),Or(Not(Var 5),And(Var 6,Or(Var 11,And(Not(Var 9),Or(Not(Var 0),Not(Var 6))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 29),Or(Not(Var 3),And(Not(Var 22),Or(Not(Var 29),And(Not(Var 27),Or(Not(Var 19),And(Var 19,Or(Not(Var 29),And(Var 13,Or(Var 8,And(Not(Var 21),Or(Var 20,And(Not(Var 14),Or(Not(Var 14),And(Not(Var 7),Or(Var 11,And(Not(Var 22),Or(Not(Var 2),And(Var 20,Or(Var 2,And(Var 2,Or(Var 16,And(Not(Var 26),Or(Var 18,And(Var 24,Or(Not(Var 13),And(Not(Var 2),Or(Var 29,And(Not(Var 24),Or(Not(Var 24),And(Not(Var 20),Or(Not(Var 1),And(Not(Var 9),Or(Not(Var 4),And(Not(Var 28),Or(Var 6,And(Not(Var 18),Or(Not(Var 0),And(Not(Var 6),Or(Var 0,And(Not(Var 22),Or(Not(Var 6),And(Not(Var 10),Or(Var 0,And(Not(Var 26),Or(Var 7,And(Var 13,Or(Not(Var 0),And(Not(Var 10),Or(Var 30,And(Not(Var 26),Or(Not(Var 14),And(Not(Var 16),Or(Var 4,And(Not(Var 8),Or(Var 29,And(Not(Var 22),Or(Var 14,And(Var 12,Or(Var 21,And(Var 7,Or(Not(Var 22),And(Var 24,Or(Var 29,And(Not(Var 31),Or(Var 14,And(Not(Var 12),Or(Var 25,And(Not(Var 20),Not(Var 29)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 12,Or(Not(Var 6),And(Not(Var 18),Or(Not(Var 8),And(Var 19,Or(Var 2,And(Var 9,Or(Var 9,And(Var 10,Or(Var 16,And(Not(Var 7),Or(Var 15,And(Var 16,Or(Var 8,And(Var 2,Or(Not(Var 9),And(Var 3,Or(Var 9,And(Var 12,Or(Not(Var 11),And(Var 9,Or(Not(Var 8),And(Not(Var 4),Or(Not(Var 1),And(Not(Var 12),Or(Var 18,And(Var 14,Or(Not(Var 19),And(Not(Var 11),Or(Var 5,And(Var 8,Or(Not(Var 12),And(Var 15,Or(Var 13,And(Var 19,Or(Var 16,And(Not(Var 19),Or(Not(Var 16),And(Var 8,Or(Not(Var 10),And(Not(Var 4),Or(Not(Var 13),And(Var 15,Or(Var 7,And(Var 19,Or(Not(Var 10),And(Not(Var 1),Or(Not(Var 4),And(Var 2,Or(Not(Var 10),And(Not(Var 16),Or(Not(Var 12),And(Not(Var 13),Or(Not(Var 16),And(Var 13,Or(Var 16,And(Var 4,Or(Var 7,And(Var 16,Or(Not(Var 17),And(Var 4,Or(Not(Var 13),And(Not(Var 5),Or(Not(Var 15),And(Var 5,Or(Var 0,And(Var 1,Or(Not(Var 6),And(Var 16,Or(Var 14,Var 15)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 4),Or(Not(Var 5),And(Var 22,Or(Var 7,And(Var 2,Or(Var 2,And(Var 29,Or(Var 12,And(Not(Var 24),Or(Not(Var 7),And(Var 16,Or(Var 23,And(Var 9,Or(Var 21,And(Var 26,Or(Var 17,And(Not(Var 18),Or(Not(Var 15),And(Not(Var 18),Or(Not(Var 23),And(Var 26,Or(Not(Var 3),And(Not(Var 20),Or(Var 28,And(Var 14,Or(Not(Var 4),And(Not(Var 12),Or(Var 15,And(Var 26,Or(Var 29,And(Var 23,Or(Var 17,And(Not(Var 22),Or(Var 14,And(Var 6,Or(Var 12,And(Not(Var 17),Or(Not(Var 24),And(Not(Var 21),Or(Var 16,And(Var 21,Or(Var 13,And(Var 5,Or(Var 12,And(Not(Var 3),Or(Var 26,And(Not(Var 9),Or(Not(Var 20),And(Not(Var 12),Or(Var 25,And(Not(Var 18),Or(Not(Var 13),And(Var 27,Or(Not(Var 11),And(Var 7,Or(Var 23,And(Var 10,Or(Not(Var 6),And(Var 29,Or(Var 13,And(Not(Var 11),Or(Not(Var 25),And(Not(Var 21),Or(Var 1,And(Var 27,Or(Var 10,And(Var 14,Or(Var 11,And(Not(Var 27),Or(Var 27,And(Var 8,Var 28))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Var 1,And(Not(Var 2),Or(Var 1,And(Not(Var 3),Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 1),And(Not(Var 5),Or(Not(Var 3),And(Not(Var 3),Or(Var 4,And(Var 3,Or(Var 4,And(Var 3,Or(Not(Var 0),And(Var 5,Or(Not(Var 5),And(Not(Var 2),Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 1),And(Not(Var 0),Or(Var 4,And(Var 3,Or(Not(Var 2),And(Var 0,Or(Not(Var 4),And(Not(Var 3),Or(Not(Var 4),And(Var 3,Or(Var 0,And(Var 5,Or(Var 5,And(Var 4,Or(Var 1,And(Not(Var 2),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 4),And(Var 1,Or(Var 0,And(Var 5,Or(Var 4,And(Not(Var 0),Or(Var 3,And(Not(Var 4),Or(Var 0,And(Var 4,Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 4,And(Var 0,Or(Not(Var 2),And(Not(Var 0),Or(Var 4,And(Var 5,Or(Var 5,And(Not(Var 5),Or(Not(Var 4),And(Not(Var 5),Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Var 3,Or(Not(Var 4),Not(Var 1))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 2),Or(Not(Var 1),And(Var 6,Or(Not(Var 6),And(Not(Var 3),Or(Var 0,And(Not(Var 1),Or(Var 4,And(Var 2,Or(Not(Var 0),And(Var 4,Or(Var 5,And(Var 4,Or(Not(Var 3),And(Not(Var 1),Or(Var 5,And(Not(Var 1),Or(Var 1,And(Not(Var 6),Or(Var 3,And(Not(Var 5),Or(Var 4,And(Not(Var 5),Or(Var 5,And(Not(Var 0),Or(Var 2,And(Not(Var 5),Or(Not(Var 2),And(Var 1,Or(Var 5,And(Var 6,Or(Not(Var 2),And(Not(Var 0),Or(Not(Var 3),And(Not(Var 0),Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 5),And(Var 6,Or(Not(Var 3),And(Not(Var 2),Or(Var 6,And(Var 0,Or(Not(Var 5),And(Not(Var 3),Or(Not(Var 1),And(Var 5,Or(Var 4,And(Not(Var 2),Or(Not(Var 2),And(Not(Var 3),Or(Var 0,And(Not(Var 6),Or(Var 4,And(Not(Var 5),Or(Var 1,And(Var 3,Or(Var 2,And(Not(Var 4),Or(Var 4,And(Not(Var 6),Or(Var 6,And(Var 1,Or(Not(Var 2),And(Var 6,Or(Var 2,And(Not(Var 3),Or(Not(Var 4),And(Var 5,Or(Var 4,And(Not(Var 0),Or(Not(Var 3),And(Not(Var 5),Not(Var 2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 9,Or(Var 31,And(Var 21,Or(Not(Var 14),And(Not(Var 29),Or(Var 11,And(Not(Var 7),Or(Not(Var 30),And(Var 6,Or(Not(Var 31),And(Not(Var 29),Or(Var 10,And(Not(Var 30),Or(Not(Var 11),And(Var 0,Or(Var 30,And(Var 13,Or(Var 29,And(Var 26,Or(Var 14,And(Not(Var 6),Or(Not(Var 23),And(Var 18,Or(Not(Var 5),And(Var 21,Or(Var 11,And(Var 28,Or(Var 26,And(Var 11,Or(Var 32,And(Var 23,Or(Not(Var 32),And(Not(Var 26),Or(Var 20,And(Not(Var 12),Or(Not(Var 34),And(Not(Var 7),Or(Var 0,And(Var 13,Or(Var 31,And(Var 4,Or(Not(Var 11),And(Var 33,Or(Var 6,And(Not(Var 3),Or(Not(Var 25),And(Not(Var 19),Or(Var 20,And(Var 18,Or(Not(Var 14),And(Not(Var 11),Or(Var 18,And(Not(Var 10),Or(Not(Var 12),And(Not(Var 5),Or(Var 26,And(Var 25,Or(Not(Var 0),And(Var 34,Or(Not(Var 3),And(Not(Var 1),Or(Var 3,And(Not(Var 34),Or(Not(Var 4),And(Var 23,Or(Var 21,And(Var 2,Or(Var 8,And(Var 17,Or(Var 24,And(Var 5,Or(Var 8,And(Not(Var 8),Or(Var 17,Var 24)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 7),And(Var 37,Or(Var 34,And(Var 19,Or(Not(Var 4),And(Var 1,Or(Var 15,And(Not(Var 4),Or(Not(Var 2),And(Var 21,Or(Var 15,And(Not(Var 11),Or(Var 19,And(Var 35,Or(Var 4,And(Not(Var 29),Or(Var 19,And(Var 18,Or(Not(Var 4),And(Not(Var 35),Or(Var 13,And(Var 11,Or(Var 37,And(Not(Var 11),Or(Var 18,And(Var 30,Or(Not(Var 36),And(Not(Var 16),Or(Not(Var 33),And(Var 26,Or(Var 27,And(Var 18,Or(Not(Var 20),And(Not(Var 17),Or(Var 29,And(Not(Var 11),Or(Not(Var 13),And(Not(Var 36),Or(Var 34,And(Var 30,Or(Var 9,And(Var 35,Or(Var 9,And(Not(Var 16),Or(Var 34,And(Not(Var 36),Or(Var 16,And(Not(Var 12),Or(Var 15,And(Var 14,Or(Var 21,And(Not(Var 33),Or(Var 23,And(Not(Var 23),Or(Not(Var 3),And(Var 35,Or(Var 10,And(Var 33,Or(Var 16,And(Var 35,Or(Var 30,And(Not(Var 31),Or(Not(Var 1),And(Not(Var 22),Or(Not(Var 2),And(Var 12,Or(Not(Var 37),And(Not(Var 8),Or(Var 26,And(Var 27,Or(Var 5,And(Var 12,Or(Var 37,And(Not(Var 16),Not(Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 24),Or(Var 7,And(Not(Var 6),Or(Var 29,And(Var 13,Or(Not(Var 5),And(Var 26,Or(Var 5,And(Var 29,Or(Var 11,And(Not(Var 17),Or(Var 21,And(Not(Var 8),Or(Var 15,And(Not(Var 8),Or(Not(Var 15),And(Var 30,Or(Var 29,And(Var 9,Or(Var 10,And(Not(Var 6),Or(Not(Var 0),And(Not(Var 24),Or(Var 30,And(Var 5,Or(Not(Var 1),And(Var 30,Or(Not(Var 3),And(Not(Var 23),Or(Var 27,And(Var 8,Or(Not(Var 11),And(Not(Var 28),Or(Var 12,And(Not(Var 18),Or(Var 0,And(Var 3,Or(Var 28,And(Not(Var 24),Or(Var 12,And(Not(Var 4),Or(Var 26,And(Not(Var 6),Or(Not(Var 6),And(Var 18,Or(Not(Var 28),And(Var 30,Or(Not(Var 1),And(Var 14,Or(Var 6,And(Not(Var 27),Or(Not(Var 14),And(Var 28,Or(Var 1,And(Var 22,Or(Var 25,And(Not(Var 18),Or(Not(Var 10),And(Var 13,Or(Var 6,And(Var 23,Or(Var 25,And(Var 3,Or(Not(Var 26),And(Var 24,Or(Not(Var 27),And(Not(Var 20),Or(Var 30,And(Not(Var 17),Or(Var 30,And(Not(Var 30),Or(Not(Var 21),And(Not(Var 18),Or(Var 14,And(Not(Var 15),Or(Var 5,Var 22)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Var 0,And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Not(Var 2),And(Var 0,Or(Not(Var 2),And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 2),Or(Not(Var 1),And(Var 0,Or(Not(Var 2),And(Not(Var 1),Or(Var 2,And(Var 0,Or(Var 1,And(Var 1,Or(Var 0,And(Var 2,Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 0),Or(Var 2,And(Not(Var 1),Or(Not(Var 2),And(Var 2,Or(Var 1,And(Var 0,Or(Var 0,And(Not(Var 1),Or(Var 2,And(Var 0,Or(Not(Var 2),And(Var 1,Or(Var 2,And(Not(Var 1),Or(Var 0,And(Var 2,Or(Not(Var 1),And(Not(Var 2),Or(Var 0,And(Not(Var 2),Or(Not(Var 0),And(Var 2,Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 1),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 1,Or(Var 2,And(Var 0,Or(Var 2,And(Var 2,Or(Not(Var 1),And(Var 1,Or(Var 2,And(Var 0,Or(Not(Var 2),And(Not(Var 2),Not(Var 2)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 12),And(Not(Var 5),Or(Not(Var 9),And(Not(Var 11),Or(Not(Var 3),And(Not(Var 8),Or(Var 4,And(Not(Var 8),Or(Var 6,And(Not(Var 0),Or(Var 9,And(Var 8,Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 1),And(Var 3,Or(Var 3,And(Var 8,Or(Var 9,And(Not(Var 11),Or(Var 12,And(Var 7,Or(Var 0,And(Not(Var 5),Or(Not(Var 9),And(Var 11,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 12),And(Var 7,Or(Not(Var 10),And(Not(Var 2),Or(Var 10,And(Not(Var 0),Or(Var 4,And(Var 12,Or(Var 6,And(Var 8,Or(Var 3,And(Var 11,Or(Not(Var 12),And(Not(Var 11),Or(Not(Var 1),And(Not(Var 11),Or(Not(Var 9),And(Not(Var 6),Or(Var 8,And(Var 0,Or(Var 1,And(Var 5,Or(Var 9,And(Var 7,Or(Var 2,And(Var 3,Or(Var 8,And(Var 1,Or(Var 9,And(Var 5,Or(Not(Var 4),And(Not(Var 11),Or(Var 3,And(Var 4,Or(Not(Var 7),And(Var 9,Or(Not(Var 11),And(Var 3,Or(Var 1,And(Var 9,Or(Not(Var 7),And(Var 9,Or(Var 0,And(Not(Var 2),Or(Var 6,And(Not(Var 6),Or(Var 4,And(Not(Var 3),Or(Not(Var 1),Not(Var 11))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 4),And(Var 0,Or(Var 2,And(Not(Var 4),Or(Var 1,And(Var 2,Or(Var 2,And(Not(Var 0),Or(Not(Var 0),And(Var 3,Or(Not(Var 4),And(Not(Var 3),Or(Var 4,And(Not(Var 4),Or(Var 1,And(Not(Var 0),Or(Not(Var 4),And(Not(Var 1),Or(Not(Var 3),And(Var 4,Or(Var 2,And(Not(Var 1),Or(Var 0,And(Var 3,Or(Var 0,And(Not(Var 4),Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 2),Or(Var 4,And(Not(Var 0),Or(Var 2,And(Var 0,Or(Var 4,And(Not(Var 2),Or(Var 2,And(Not(Var 2),Or(Not(Var 1),And(Var 3,Or(Not(Var 2),And(Var 3,Or(Var 4,And(Var 2,Or(Not(Var 2),And(Var 0,Or(Var 0,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 3),Or(Var 2,And(Not(Var 0),Or(Not(Var 2),And(Not(Var 4),Or(Not(Var 0),And(Var 2,Or(Not(Var 0),And(Var 0,Or(Var 4,And(Not(Var 0),Or(Var 2,And(Var 2,Or(Not(Var 1),And(Var 3,Or(Not(Var 1),And(Var 4,Or(Not(Var 2),And(Not(Var 2),Or(Not(Var 0),And(Var 2,Or(Not(Var 3),And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 2,And(Var 1,Var 0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 7),And(Var 7,Or(Var 7,And(Not(Var 8),Or(Var 7,And(Var 0,Or(Not(Var 9),And(Not(Var 2),Or(Not(Var 9),And(Var 9,Or(Not(Var 5),And(Not(Var 0),Or(Not(Var 7),And(Var 4,Or(Not(Var 3),And(Not(Var 7),Or(Not(Var 8),And(Not(Var 6),Or(Var 5,And(Not(Var 5),Or(Var 7,And(Not(Var 6),Or(Var 9,And(Not(Var 6),Or(Var 8,And(Not(Var 4),Or(Not(Var 8),And(Var 6,Or(Not(Var 6),And(Var 7,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 1),And(Var 5,Or(Var 2,And(Var 8,Or(Var 0,And(Not(Var 7),Or(Not(Var 0),And(Not(Var 2),Or(Not(Var 6),And(Not(Var 7),Or(Var 7,And(Not(Var 0),Or(Not(Var 2),And(Not(Var 5),Or(Var 7,And(Not(Var 1),Or(Var 1,And(Not(Var 5),Or(Not(Var 5),And(Not(Var 1),Or(Var 7,And(Not(Var 4),Or(Var 4,And(Var 3,Or(Not(Var 3),And(Not(Var 3),Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 0),And(Var 6,Or(Not(Var 8),And(Var 1,Or(Not(Var 7),And(Var 6,Or(Var 7,And(Not(Var 5),Or(Var 7,And(Var 2,Or(Var 9,And(Var 0,Or(Not(Var 5),And(Not(Var 1),Or(Var 5,And(Not(Var 6),Or(Not(Var 9),Not(Var 7))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 1,And(Not(Var 7),Or(Var 24,And(Not(Var 10),Or(Var 25,And(Var 9,Or(Not(Var 23),And(Not(Var 13),Or(Var 9,And(Var 8,Or(Not(Var 12),And(Not(Var 10),Or(Not(Var 25),And(Var 18,Or(Var 28,And(Var 27,Or(Not(Var 20),And(Var 27,Or(Not(Var 2),And(Var 7,Or(Not(Var 20),And(Var 20,Or(Var 19,And(Not(Var 18),Or(Var 6,And(Not(Var 3),Or(Var 5,And(Var 11,Or(Var 28,And(Var 10,Or(Not(Var 12),And(Var 7,Or(Var 27,And(Var 5,Or(Not(Var 4),And(Var 20,Or(Var 5,And(Var 15,Or(Var 16,And(Var 1,Or(Not(Var 21),And(Not(Var 23),Or(Var 8,And(Not(Var 23),Or(Not(Var 15),And(Not(Var 28),Or(Not(Var 5),And(Not(Var 4),Or(Not(Var 28),And(Not(Var 9),Or(Var 8,And(Not(Var 7),Or(Var 12,And(Var 13,Or(Not(Var 0),And(Not(Var 30),Or(Not(Var 16),And(Var 18,Or(Var 16,And(Var 1,Or(Not(Var 14),And(Var 20,Or(Not(Var 23),And(Var 22,Or(Var 2,And(Var 10,Or(Not(Var 24),And(Var 16,Or(Not(Var 3),And(Var 22,Or(Not(Var 4),And(Not(Var 9),Or(Not(Var 27),And(Var 12,Or(Var 4,And(Var 8,Or(Not(Var 10),And(Var 25,Or(Var 26,And(Var 27,Var 10))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 13,Or(Not(Var 6),And(Not(Var 7),Or(Var 8,And(Not(Var 21),Or(Var 13,And(Var 11,Or(Var 8,And(Not(Var 11),Or(Var 22,And(Not(Var 9),Or(Not(Var 22),And(Not(Var 15),Or(Not(Var 0),And(Not(Var 13),Or(Var 3,And(Not(Var 16),Or(Not(Var 7),And(Var 18,Or(Not(Var 20),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Var 19,Or(Var 13,And(Not(Var 15),Or(Not(Var 12),And(Var 7,Or(Not(Var 9),And(Not(Var 18),Or(Var 2,And(Not(Var 4),Or(Var 11,And(Not(Var 20),Or(Var 4,And(Not(Var 9),Or(Var 0,And(Not(Var 14),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 3),Or(Var 0,And(Not(Var 2),Or(Not(Var 11),And(Not(Var 18),Or(Not(Var 6),And(Not(Var 18),Or(Var 1,And(Not(Var 11),Or(Var 1,And(Var 21,Or(Not(Var 5),And(Var 22,Or(Var 21,And(Var 11,Or(Var 13,And(Not(Var 9),Or(Var 8,And(Not(Var 22),Or(Not(Var 22),And(Not(Var 7),Or(Not(Var 4),And(Var 18,Or(Not(Var 0),And(Not(Var 3),Or(Var 19,And(Not(Var 14),Or(Var 12,And(Var 10,Or(Not(Var 11),And(Not(Var 22),Or(Not(Var 16),And(Not(Var 2),Or(Var 11,And(Var 17,Or(Var 4,And(Var 4,Or(Not(Var 3),And(Var 17,Or(Not(Var 13),Not(Var 5))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 15,Or(Not(Var 3),And(Not(Var 10),Or(Var 1,And(Not(Var 15),Or(Not(Var 5),And(Not(Var 1),Or(Var 6,And(Not(Var 15),Or(Not(Var 1),And(Not(Var 13),Or(Var 12,And(Var 13,Or(Var 10,And(Var 5,Or(Not(Var 0),And(Not(Var 13),Or(Not(Var 14),And(Var 12,Or(Not(Var 2),And(Var 15,Or(Not(Var 15),And(Var 1,Or(Var 3,And(Var 5,Or(Var 10,And(Var 7,Or(Var 12,And(Var 9,Or(Var 12,And(Var 1,Or(Var 13,And(Var 11,Or(Var 3,And(Var 6,Or(Var 9,And(Not(Var 12),Or(Not(Var 11),And(Not(Var 8),Or(Not(Var 3),And(Not(Var 9),Or(Var 9,And(Var 5,Or(Var 8,And(Var 11,Or(Not(Var 11),And(Var 3,Or(Not(Var 1),And(Not(Var 12),Or(Var 7,And(Var 15,Or(Var 6,And(Not(Var 11),Or(Not(Var 13),And(Not(Var 6),Or(Not(Var 1),And(Var 12,Or(Var 0,And(Not(Var 11),Or(Not(Var 7),And(Var 12,Or(Not(Var 13),And(Var 11,Or(Var 10,And(Var 12,Or(Not(Var 9),And(Not(Var 10),Or(Not(Var 12),And(Not(Var 8),Or(Var 13,And(Var 10,Or(Not(Var 3),And(Var 2,Or(Var 14,And(Var 14,Or(Var 4,And(Var 5,Or(Not(Var 9),And(Not(Var 13),Or(Var 5,And(Var 0,Or(Var 0,And(Var 10,Var 12))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Not(Var 3),And(Not(Var 3),Or(Not(Var 5),And(Not(Var 0),Or(Not(Var 2),And(Not(Var 3),Or(Var 5,And(Var 5,Or(Not(Var 1),And(Not(Var 4),Or(Not(Var 0),And(Not(Var 3),Or(Var 2,And(Not(Var 5),Or(Var 4,And(Var 2,Or(Not(Var 3),And(Not(Var 1),Or(Not(Var 4),And(Not(Var 2),Or(Var 3,And(Not(Var 1),Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 5),And(Not(Var 1),Or(Var 1,And(Not(Var 4),Or(Not(Var 2),And(Var 5,Or(Var 1,And(Not(Var 2),Or(Var 5,And(Var 2,Or(Var 2,And(Not(Var 4),Or(Not(Var 2),And(Not(Var 3),Or(Var 5,And(Not(Var 5),Or(Var 5,And(Not(Var 3),Or(Not(Var 5),And(Not(Var 2),Or(Var 2,And(Not(Var 0),Or(Not(Var 4),And(Var 5,Or(Var 5,And(Var 0,Or(Not(Var 4),And(Var 3,Or(Not(Var 3),And(Var 3,Or(Not(Var 5),And(Not(Var 1),Or(Var 2,And(Var 1,Or(Var 4,And(Not(Var 1),Or(Not(Var 5),And(Not(Var 2),Or(Not(Var 2),And(Var 2,Or(Not(Var 3),And(Not(Var 1),Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 0),And(Var 4,Or(Var 3,And(Not(Var 1),Or(Var 2,And(Var 5,Or(Var 5,And(Not(Var 2),Or(Var 5,And(Not(Var 4),Or(Not(Var 4),And(Var 0,Or(Not(Var 4),And(Var 2,Or(Not(Var 0),Not(Var 2))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 11),Or(Var 12,And(Var 21,Or(Not(Var 0),And(Var 18,Or(Var 6,And(Var 1,Or(Not(Var 24),And(Not(Var 6),Or(Not(Var 8),And(Not(Var 16),Or(Var 10,And(Not(Var 14),Or(Not(Var 24),And(Var 24,Or(Not(Var 24),And(Not(Var 14),Or(Var 17,And(Not(Var 25),Or(Var 6,And(Var 0,Or(Not(Var 0),And(Var 7,Or(Var 20,And(Var 2,Or(Not(Var 4),And(Var 6,Or(Not(Var 19),And(Var 10,Or(Var 4,And(Var 17,Or(Not(Var 19),And(Var 9,Or(Var 21,And(Not(Var 10),Or(Not(Var 10),And(Var 22,Or(Var 20,And(Not(Var 7),Or(Var 25,And(Var 4,Or(Var 12,And(Var 4,Or(Not(Var 22),And(Not(Var 23),Or(Not(Var 0),And(Not(Var 16),Or(Var 11,And(Not(Var 2),Or(Not(Var 0),And(Var 16,Or(Var 9,And(Not(Var 10),Or(Not(Var 12),And(Not(Var 11),Or(Not(Var 14),And(Var 18,Or(Var 14,And(Var 10,Or(Var 25,And(Var 18,Or(Var 25,And(Not(Var 23),Or(Not(Var 7),And(Var 17,Or(Var 8,And(Var 24,Or(Not(Var 23),And(Var 7,Or(Not(Var 15),And(Not(Var 26),Or(Not(Var 23),And(Var 4,Or(Not(Var 17),And(Var 10,Or(Var 11,And(Not(Var 14),Or(Not(Var 12),And(Not(Var 18),Or(Not(Var 23),And(Var 24,Or(Not(Var 18),And(Not(Var 1),Or(Not(Var 11),And(Not(Var 5),Not(Var 4)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 37,Or(Var 32,And(Var 19,Or(Not(Var 25),And(Var 7,Or(Var 3,And(Not(Var 40),Or(Var 4,And(Not(Var 23),Or(Var 23,And(Not(Var 30),Or(Var 14,And(Var 1,Or(Not(Var 28),And(Not(Var 21),Or(Not(Var 2),And(Var 35,Or(Not(Var 11),And(Var 40,Or(Not(Var 5),And(Var 39,Or(Not(Var 29),And(Not(Var 1),Or(Var 34,And(Var 28,Or(Not(Var 20),And(Var 34,Or(Not(Var 14),And(Not(Var 29),Or(Not(Var 13),And(Var 40,Or(Not(Var 16),And(Var 9,Or(Var 33,And(Var 26,Or(Not(Var 24),And(Var 4,Or(Var 27,And(Var 24,Or(Not(Var 3),And(Var 9,Or(Not(Var 31),And(Not(Var 23),Or(Not(Var 16),And(Not(Var 16),Or(Not(Var 23),And(Not(Var 2),Or(Var 26,And(Not(Var 35),Or(Not(Var 4),And(Var 23,Or(Var 23,And(Var 29,Or(Var 14,And(Var 14,Or(Var 18,And(Var 5,Or(Var 34,And(Var 5,Or(Var 6,And(Var 18,Or(Not(Var 9),And(Not(Var 6),Or(Not(Var 14),And(Var 20,Or(Var 35,And(Not(Var 21),Or(Var 3,And(Not(Var 3),Or(Not(Var 31),And(Var 5,Or(Var 36,And(Not(Var 7),Or(Not(Var 19),And(Var 35,Or(Var 23,And(Var 8,Or(Var 39,And(Not(Var 34),Or(Not(Var 17),And(Var 25,Or(Var 6,And(Not(Var 4),Or(Var 35,And(Not(Var 9),Or(Var 40,Var 40)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 10),Or(Not(Var 17),And(Var 16,Or(Not(Var 21),And(Var 19,Or(Not(Var 22),And(Var 21,Or(Not(Var 5),And(Var 6,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 2),And(Not(Var 10),Or(Not(Var 23),And(Not(Var 8),Or(Var 5,And(Var 13,Or(Var 17,And(Not(Var 18),Or(Not(Var 24),And(Not(Var 14),Or(Var 14,And(Var 9,Or(Var 11,And(Var 10,Or(Var 14,And(Not(Var 21),Or(Not(Var 21),And(Var 12,Or(Var 15,And(Not(Var 6),Or(Not(Var 4),And(Not(Var 21),Or(Var 4,And(Var 1,Or(Var 19,And(Not(Var 9),Or(Var 20,And(Not(Var 8),Or(Not(Var 18),And(Not(Var 18),Or(Var 19,And(Not(Var 18),Or(Not(Var 11),And(Not(Var 18),Or(Var 17,And(Var 13,Or(Not(Var 24),And(Var 5,Or(Var 11,And(Var 3,Or(Not(Var 21),And(Var 1,Or(Not(Var 8),And(Not(Var 1),Or(Not(Var 6),And(Var 11,Or(Not(Var 18),And(Var 8,Or(Not(Var 5),And(Var 9,Or(Var 4,And(Not(Var 0),Or(Not(Var 8),And(Var 2,Or(Not(Var 1),And(Var 23,Or(Var 8,And(Not(Var 12),Or(Not(Var 6),And(Not(Var 3),Or(Var 0,And(Not(Var 18),Or(Var 3,And(Var 12,Or(Var 0,And(Not(Var 16),Or(Not(Var 21),And(Var 21,Or(Not(Var 15),And(Not(Var 6),Or(Not(Var 17),And(Var 15,Or(Var 2,And(Not(Var 7),Or(Var 8,And(Var 23,Var 6))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Var 0,And(Var 2,Or(Var 1,And(Not(Var 5),Or(Not(Var 0),And(Not(Var 3),Or(Var 5,And(Var 1,Or(Var 3,And(Var 2,Or(Not(Var 2),And(Var 1,Or(Var 5,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 1),Or(Var 2,And(Not(Var 5),Or(Not(Var 2),And(Not(Var 1),Or(Not(Var 3),And(Not(Var 5),Or(Not(Var 3),And(Var 5,Or(Not(Var 5),And(Var 2,Or(Var 0,And(Not(Var 3),Or(Var 0,And(Not(Var 5),Or(Not(Var 4),And(Var 5,Or(Var 5,And(Var 0,Or(Var 2,And(Var 0,Or(Var 5,And(Var 1,Or(Var 3,And(Var 1,Or(Not(Var 5),And(Not(Var 5),Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 3),And(Not(Var 0),Or(Var 1,And(Var 2,Or(Var 1,And(Var 5,Or(Not(Var 5),And(Not(Var 4),Or(Not(Var 3),And(Var 4,Or(Var 0,And(Not(Var 1),Or(Var 0,And(Var 3,Or(Var 5,And(Var 2,Or(Not(Var 3),And(Var 2,Or(Var 5,And(Var 3,Or(Var 4,And(Not(Var 5),Or(Var 4,And(Var 3,Or(Var 4,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 4),Or(Var 2,And(Not(Var 2),Or(Var 4,And(Not(Var 2),Or(Not(Var 2),And(Var 1,Or(Var 5,And(Var 4,Or(Var 2,And(Not(Var 2),Or(Not(Var 3),And(Not(Var 5),Or(Var 5,And(Not(Var 5),Or(Not(Var 4),Not(Var 1))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 2),Or(Not(Var 0),And(Var 0,Or(Not(Var 3),And(Var 2,Or(Not(Var 1),And(Var 2,Or(Not(Var 2),And(Not(Var 2),Or(Not(Var 1),And(Var 0,Or(Not(Var 3),And(Not(Var 1),Or(Var 0,And(Var 1,Or(Var 2,And(Var 0,Or(Var 2,And(Not(Var 2),Or(Not(Var 2),And(Not(Var 0),Or(Var 0,And(Not(Var 1),Or(Var 2,And(Not(Var 2),Or(Not(Var 0),And(Not(Var 2),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 3),Or(Var 3,And(Not(Var 2),Or(Not(Var 3),And(Var 1,Or(Not(Var 2),And(Not(Var 0),Or(Var 1,And(Var 1,Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 3),And(Var 2,Or(Var 0,And(Var 2,Or(Var 1,And(Not(Var 0),Or(Var 3,And(Var 3,Or(Not(Var 0),And(Var 3,Or(Var 1,And(Var 2,Or(Not(Var 0),And(Var 0,Or(Not(Var 2),And(Not(Var 3),Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Var 3,And(Not(Var 1),Or(Not(Var 0),And(Not(Var 3),Or(Var 3,And(Not(Var 1),Or(Var 3,And(Var 3,Or(Var 1,And(Var 2,Or(Var 3,And(Not(Var 1),Or(Not(Var 2),And(Var 1,Or(Var 2,And(Not(Var 1),Or(Not(Var 0),And(Var 3,Or(Not(Var 2),And(Var 3,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 3,Var 3))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Not(Var 13),And(Not(Var 6),Or(Var 3,And(Var 14,Or(Not(Var 12),And(Var 10,Or(Var 6,And(Not(Var 15),Or(Not(Var 9),And(Var 5,Or(Not(Var 18),And(Var 7,Or(Var 12,And(Not(Var 20),Or(Not(Var 9),And(Var 12,Or(Not(Var 23),And(Not(Var 12),Or(Var 15,And(Var 16,Or(Var 19,And(Var 9,Or(Var 21,And(Var 21,Or(Not(Var 18),And(Var 20,Or(Not(Var 7),And(Var 18,Or(Var 15,And(Var 10,Or(Var 14,And(Not(Var 14),Or(Var 21,And(Not(Var 5),Or(Not(Var 9),And(Var 21,Or(Not(Var 5),And(Not(Var 0),Or(Var 2,And(Not(Var 6),Or(Var 2,And(Var 19,Or(Var 10,And(Not(Var 10),Or(Var 20,And(Not(Var 5),Or(Var 21,And(Var 22,Or(Var 8,And(Var 10,Or(Var 21,And(Var 16,Or(Not(Var 3),And(Var 22,Or(Not(Var 10),And(Not(Var 1),Or(Not(Var 10),And(Not(Var 22),Or(Not(Var 13),And(Var 10,Or(Not(Var 12),And(Var 3,Or(Not(Var 17),And(Var 12,Or(Not(Var 19),And(Not(Var 4),Or(Not(Var 14),And(Not(Var 22),Or(Var 22,And(Not(Var 19),Or(Var 7,And(Var 12,Or(Var 0,And(Not(Var 21),Or(Not(Var 5),And(Not(Var 6),Or(Not(Var 4),And(Var 19,Or(Not(Var 4),And(Var 5,Or(Var 9,And(Var 14,Or(Not(Var 10),And(Var 9,Or(Not(Var 22),And(Var 23,Or(Not(Var 12),And(Var 22,Or(Var 19,Var 1)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 1),Or(Not(Var 4),And(Var 4,Or(Var 8,And(Not(Var 3),Or(Var 1,And(Not(Var 1),Or(Var 1,And(Not(Var 7),Or(Var 10,And(Var 7,Or(Var 2,And(Var 10,Or(Var 3,And(Var 8,Or(Var 1,And(Var 5,Or(Not(Var 1),And(Var 1,Or(Var 8,And(Var 7,Or(Not(Var 8),And(Not(Var 4),Or(Not(Var 2),And(Var 2,Or(Var 2,And(Var 8,Or(Not(Var 5),And(Not(Var 3),Or(Var 4,And(Not(Var 2),Or(Var 7,And(Var 10,Or(Var 0,And(Not(Var 4),Or(Var 5,And(Var 8,Or(Var 8,And(Var 4,Or(Var 9,And(Var 0,Or(Var 2,And(Var 0,Or(Var 7,And(Not(Var 0),Or(Var 6,And(Var 3,Or(Not(Var 1),And(Var 6,Or(Not(Var 8),And(Var 1,Or(Var 7,And(Not(Var 9),Or(Not(Var 8),And(Var 7,Or(Not(Var 1),And(Var 6,Or(Not(Var 6),And(Var 5,Or(Not(Var 7),And(Not(Var 6),Or(Not(Var 10),And(Var 0,Or(Not(Var 1),And(Not(Var 9),Or(Var 1,And(Not(Var 5),Or(Var 7,And(Not(Var 7),Or(Var 1,And(Var 4,Or(Not(Var 2),And(Not(Var 9),Or(Not(Var 1),And(Not(Var 2),Or(Var 7,And(Var 1,Or(Not(Var 10),And(Var 5,Or(Var 5,And(Not(Var 7),Or(Var 9,And(Not(Var 10),Or(Var 2,And(Not(Var 10),Or(Var 5,And(Var 9,Or(Not(Var 3),And(Not(Var 4),Or(Not(Var 5),And(Var 8,Var 0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 4),Or(Var 5,And(Var 5,Or(Not(Var 4),And(Not(Var 2),Or(Not(Var 0),And(Not(Var 3),Or(Not(Var 3),And(Var 2,Or(Var 0,And(Var 4,Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 0),And(Var 4,Or(Not(Var 3),And(Var 0,Or(Not(Var 2),And(Var 1,Or(Var 1,And(Var 0,Or(Var 4,And(Var 2,Or(Var 4,And(Var 1,Or(Not(Var 0),And(Not(Var 3),Or(Var 5,And(Var 4,Or(Var 2,And(Not(Var 4),Or(Not(Var 3),And(Not(Var 2),Or(Var 2,And(Var 0,Or(Var 1,And(Not(Var 5),Or(Var 4,And(Var 1,Or(Not(Var 0),And(Not(Var 4),Or(Var 2,And(Not(Var 5),Or(Var 2,And(Not(Var 3),Or(Var 3,And(Var 3,Or(Not(Var 2),And(Not(Var 2),Or(Var 1,And(Not(Var 1),Or(Var 2,And(Var 4,Or(Var 5,And(Not(Var 4),Or(Not(Var 4),And(Not(Var 1),Or(Var 0,And(Var 1,Or(Not(Var 4),And(Var 2,Or(Var 1,And(Var 1,Or(Var 3,And(Var 0,Or(Var 1,And(Not(Var 4),Or(Var 0,And(Var 2,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 2,Or(Not(Var 4),And(Not(Var 5),Or(Not(Var 4),And(Var 0,Or(Not(Var 3),And(Not(Var 0),Or(Var 2,And(Var 0,Or(Not(Var 2),And(Not(Var 5),Or(Var 4,And(Var 2,Or(Var 0,And(Not(Var 1),Or(Var 5,And(Var 5,Or(Not(Var 4),And(Var 3,Or(Not(Var 0),Not(Var 2))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 8,Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 9),And(Not(Var 9),Or(Not(Var 7),And(Not(Var 5),Or(Not(Var 2),And(Var 11,Or(Var 0,And(Not(Var 3),Or(Not(Var 6),And(Not(Var 8),Or(Var 2,And(Var 8,Or(Not(Var 9),And(Var 4,Or(Not(Var 9),And(Not(Var 6),Or(Not(Var 2),And(Not(Var 11),Or(Var 4,And(Var 1,Or(Var 9,And(Var 8,Or(Var 0,And(Var 6,Or(Var 2,And(Var 11,Or(Var 3,And(Var 8,Or(Not(Var 1),And(Var 3,Or(Not(Var 11),And(Not(Var 11),Or(Var 0,And(Var 6,Or(Var 9,And(Var 6,Or(Var 7,And(Var 9,Or(Var 2,And(Not(Var 9),Or(Var 8,And(Not(Var 3),Or(Not(Var 2),And(Var 9,Or(Not(Var 3),And(Var 10,Or(Not(Var 8),And(Not(Var 9),Or(Var 8,And(Not(Var 0),Or(Not(Var 7),And(Var 7,Or(Not(Var 8),And(Not(Var 0),Or(Not(Var 5),And(Not(Var 11),Or(Var 0,And(Not(Var 8),Or(Not(Var 11),And(Not(Var 4),Or(Not(Var 9),And(Var 4,Or(Var 10,And(Var 7,Or(Var 3,And(Not(Var 3),Or(Not(Var 6),And(Not(Var 1),Or(Not(Var 6),And(Var 1,Or(Var 7,And(Var 9,Or(Var 4,And(Var 2,Or(Var 10,And(Not(Var 8),Or(Var 9,And(Var 9,Or(Var 10,And(Not(Var 2),Or(Var 10,And(Var 4,Or(Not(Var 4),And(Not(Var 9),Or(Not(Var 1),And(Not(Var 10),Or(Var 6,And(Not(Var 7),Or(Not(Var 5),And(Not(Var 10),Not(Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 1,Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Not(Var 0),And(Var 1,Or(Not(Var 0),And(Var 0,Or(Var 1,And(Not(Var 0),Or(Var 0,And(Not(Var 1),Or(Var 0,And(Var 1,Or(Var 0,And(Var 1,Or(Var 1,And(Not(Var 1),Or(Not(Var 1),And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 1,Or(Var 0,And(Not(Var 0),Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Var 1,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 0,And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 1),Or(Not(Var 0),And(Var 1,Or(Not(Var 1),And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 1,And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Not(Var 1),And(Not(Var 1),Or(Not(Var 0),And(Not(Var 1),Or(Var 0,And(Var 1,Or(Not(Var 0),And(Var 0,Or(Not(Var 1),And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Not(Var 1),And(Var 1,Or(Var 0,And(Not(Var 0),Or(Var 1,And(Not(Var 1),Or(Not(Var 0),And(Var 0,Or(Var 1,And(Var 0,Or(Var 1,And(Not(Var 1),Or(Var 0,Var 0)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 5,Or(Var 18,And(Var 7,Or(Not(Var 1),And(Not(Var 18),Or(Not(Var 16),And(Not(Var 0),Or(Not(Var 14),And(Var 20,Or(Var 2,And(Var 16,Or(Not(Var 1),And(Var 2,Or(Not(Var 11),And(Not(Var 20),Or(Not(Var 3),And(Not(Var 20),Or(Var 8,And(Var 21,Or(Not(Var 3),And(Var 17,Or(Var 20,And(Var 4,Or(Var 6,And(Var 14,Or(Not(Var 2),And(Not(Var 8),Or(Not(Var 10),And(Not(Var 13),Or(Var 10,And(Var 16,Or(Not(Var 10),And(Var 7,Or(Not(Var 21),And(Not(Var 11),Or(Var 18,And(Not(Var 8),Or(Not(Var 13),And(Not(Var 10),Or(Not(Var 2),And(Var 15,Or(Not(Var 19),And(Var 14,Or(Var 8,And(Not(Var 4),Or(Not(Var 12),And(Var 6,Or(Var 16,And(Not(Var 19),Or(Var 4,And(Var 19,Or(Not(Var 13),And(Not(Var 5),Or(Not(Var 11),And(Var 20,Or(Var 14,And(Not(Var 18),Or(Var 10,And(Var 20,Or(Not(Var 8),And(Var 21,Or(Var 15,And(Not(Var 10),Or(Not(Var 1),And(Not(Var 3),Or(Not(Var 13),And(Not(Var 6),Or(Not(Var 12),And(Not(Var 16),Or(Not(Var 11),And(Not(Var 13),Or(Var 17,And(Not(Var 9),Or(Var 21,And(Var 0,Or(Var 2,And(Not(Var 14),Or(Not(Var 4),And(Not(Var 16),Or(Not(Var 21),And(Var 7,Or(Var 7,And(Not(Var 2),Or(Var 4,And(Var 11,Or(Var 6,And(Var 11,Or(Var 8,And(Var 2,Or(Not(Var 11),And(Not(Var 9),Or(Not(Var 20),And(Not(Var 11),Or(Var 19,And(Var 2,Var 4))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 0),Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 0),Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Not(Var 0),And(Var 0,Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 0,Or(Var 0,And(Not(Var 0),Or(Var 0,And(Var 0,Or(Not(Var 0),And(Not(Var 0),Or(Var 0,And(Not(Var 0),Or(Not(Var 0),Not(Var 0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 7),Or(Not(Var 8),And(Not(Var 0),Or(Var 5,And(Not(Var 17),Or(Not(Var 9),And(Not(Var 5),Or(Not(Var 0),And(Var 16,Or(Var 7,And(Not(Var 9),Or(Not(Var 6),And(Var 16,Or(Not(Var 9),And(Var 15,Or(Var 20,And(Not(Var 0),Or(Not(Var 17),And(Not(Var 6),Or(Not(Var 15),And(Var 9,Or(Not(Var 18),And(Var 14,Or(Var 6,And(Var 21,Or(Not(Var 0),And(Not(Var 8),Or(Not(Var 18),And(Not(Var 13),Or(Var 1,And(Var 2,Or(Not(Var 9),And(Not(Var 2),Or(Var 12,And(Var 8,Or(Var 19,And(Not(Var 1),Or(Not(Var 21),And(Var 6,Or(Not(Var 21),And(Not(Var 10),Or(Not(Var 8),And(Not(Var 6),Or(Not(Var 3),And(Var 15,Or(Not(Var 8),And(Not(Var 2),Or(Not(Var 18),And(Var 13,Or(Var 12,And(Var 0,Or(Var 8,And(Var 17,Or(Var 4,And(Var 13,Or(Var 9,And(Var 1,Or(Not(Var 17),And(Not(Var 4),Or(Not(Var 20),And(Var 12,Or(Var 7,And(Not(Var 12),Or(Var 12,And(Var 16,Or(Var 3,And(Var 13,Or(Var 21,And(Not(Var 9),Or(Var 14,And(Var 14,Or(Not(Var 10),And(Not(Var 14),Or(Not(Var 7),And(Var 12,Or(Var 2,And(Var 9,Or(Not(Var 6),And(Not(Var 1),Or(Not(Var 11),And(Not(Var 13),Or(Var 2,And(Var 7,Or(Not(Var 11),And(Not(Var 14),Or(Not(Var 10),And(Var 22,Or(Var 11,And(Not(Var 8),Or(Var 18,And(Not(Var 12),Or(Not(Var 21),And(Not(Var 0),Or(Not(Var 15),And(Var 20,Or(Not(Var 19),And(Var 6,Var 6))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 12),Or(Var 1,And(Not(Var 6),Or(Var 11,And(Var 1,Or(Var 15,And(Var 7,Or(Not(Var 11),And(Var 4,Or(Not(Var 2),And(Var 5,Or(Not(Var 3),And(Not(Var 11),Or(Not(Var 7),And(Var 11,Or(Not(Var 9),And(Var 4,Or(Var 7,And(Not(Var 3),Or(Not(Var 6),And(Var 5,Or(Not(Var 12),And(Var 9,Or(Not(Var 5),And(Var 5,Or(Not(Var 2),And(Var 7,Or(Var 0,And(Not(Var 9),Or(Var 8,And(Not(Var 9),Or(Not(Var 8),And(Not(Var 13),Or(Var 1,And(Var 10,Or(Not(Var 9),And(Not(Var 15),Or(Var 9,And(Var 3,Or(Not(Var 2),And(Var 6,Or(Var 6,And(Not(Var 4),Or(Var 0,And(Var 3,Or(Not(Var 6),And(Not(Var 1),Or(Var 4,And(Not(Var 0),Or(Not(Var 15),And(Not(Var 11),Or(Not(Var 10),And(Var 3,Or(Var 15,And(Var 3,Or(Not(Var 12),And(Var 11,Or(Not(Var 5),And(Not(Var 12),Or(Not(Var 6),And(Var 10,Or(Not(Var 3),And(Var 14,Or(Not(Var 14),And(Not(Var 4),Or(Var 1,And(Not(Var 4),Or(Not(Var 1),And(Var 11,Or(Not(Var 2),And(Var 1,Or(Not(Var 10),And(Not(Var 15),Or(Not(Var 4),And(Var 2,Or(Var 12,And(Not(Var 12),Or(Var 6,And(Var 9,Or(Var 10,And(Not(Var 5),Or(Not(Var 7),And(Var 3,Or(Var 4,And(Not(Var 2),Or(Var 11,And(Var 11,Or(Var 6,And(Var 6,Or(Var 2,And(Not(Var 14),Or(Var 12,And(Not(Var 5),Or(Var 5,And(Not(Var 12),Or(Not(Var 0),And(Var 11,Or(Var 1,Var 10)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Not(Var 11),Or(Not(Var 4),And(Not(Var 26),Or(Not(Var 22),And(Var 17,Or(Not(Var 13),And(Not(Var 2),Or(Var 19,And(Var 22,Or(Not(Var 10),And(Not(Var 18),Or(Var 15,And(Not(Var 3),Or(Var 12,And(Not(Var 15),Or(Not(Var 18),And(Var 10,Or(Not(Var 23),And(Not(Var 4),Or(Not(Var 25),And(Not(Var 11),Or(Var 3,And(Var 24,Or(Var 25,And(Not(Var 15),Or(Not(Var 17),And(Not(Var 23),Or(Not(Var 24),And(Not(Var 10),Or(Not(Var 9),And(Not(Var 0),Or(Not(Var 22),And(Var 0,Or(Var 23,And(Not(Var 8),Or(Var 18,And(Var 4,Or(Not(Var 1),And(Var 18,Or(Not(Var 23),And(Var 21,Or(Not(Var 18),And(Not(Var 14),Or(Not(Var 9),And(Not(Var 26),Or(Var 19,And(Var 19,Or(Not(Var 7),And(Var 9,Or(Not(Var 6),And(Var 11,Or(Not(Var 10),And(Not(Var 4),Or(Not(Var 17),And(Not(Var 8),Or(Not(Var 18),And(Var 4,Or(Not(Var 17),And(Not(Var 9),Or(Not(Var 4),And(Not(Var 0),Or(Not(Var 2),And(Var 2,Or(Not(Var 7),And(Var 15,Or(Not(Var 15),And(Var 13,Or(Var 24,And(Var 13,Or(Not(Var 6),And(Var 9,Or(Not(Var 8),And(Var 13,Or(Var 24,And(Not(Var 26),Or(Not(Var 10),And(Var 25,Or(Not(Var 1),And(Var 6,Or(Not(Var 2),And(Not(Var 10),Or(Not(Var 4),And(Not(Var 12),Or(Var 10,And(Not(Var 11),Or(Not(Var 21),And(Not(Var 21),Or(Not(Var 14),And(Var 3,Or(Var 18,And(Not(Var 16),Or(Var 23,And(Var 13,Or(Not(Var 8),And(Var 5,Or(Not(Var 21),And(Var 4,Or(Not(Var 6),And(Not(Var 9),Not(Var 19)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
(And(Var 0,Or(Not(Var 22),And(Not(Var 3),Or(Var 8,And(Not(Var 26),Or(Not(Var 9),And(Var 12,Or(Not(Var 8),And(Var 6,Or(Not(Var 6),And(Not(Var 28),Or(Var 19,And(Var 27,Or(Var 13,And(Var 26,Or(Not(Var 26),And(Var 13,Or(Not(Var 11),And(Not(Var 18),Or(Not(Var 8),And(Var 20,Or(Not(Var 1),And(Var 25,Or(Not(Var 3),And(Var 3,Or(Var 3,And(Var 13,Or(Not(Var 1),And(Not(Var 16),Or(Not(Var 13),And(Not(Var 0),Or(Var 27,And(Var 23,Or(Var 2,And(Not(Var 3),Or(Var 8,And(Not(Var 6),Or(Not(Var 24),And(Var 16,Or(Var 16,And(Var 27,Or(Not(Var 7),And(Var 16,Or(Not(Var 11),And(Not(Var 8),Or(Not(Var 11),And(Var 14,Or(Var 9,And(Var 10,Or(Not(Var 0),And(Not(Var 7),Or(Var 17,And(Var 19,Or(Var 1,And(Not(Var 16),Or(Var 10,And(Var 25,Or(Not(Var 3),And(Var 5,Or(Var 9,And(Not(Var 27),Or(Var 21,And(Var 17,Or(Not(Var 14),And(Var 10,Or(Not(Var 11),And(Not(Var 28),Or(Var 10,And(Var 13,Or(Var 5,And(Not(Var 6),Or(Var 20,And(Var 4,Or(Not(Var 25),And(Var 20,Or(Not(Var 4),And(Not(Var 13),Or(Var 10,And(Not(Var 16),Or(Var 16,And(Not(Var 2),Or(Not(Var 25),And(Var 18,Or(Not(Var 4),And(Var 10,Or(Not(Var 14),And(Not(Var 5),Or(Not(Var 8),And(Var 20,Or(Not(Var 18),And(Var 9,Or(Not(Var 5),And(Var 27,Or(Not(Var 7),And(Not(Var 7),Or(Not(Var 5),And(Var 5,Or(Not(Var 12),And(Not(Var 26),Or(Var 18,Var 8)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
|]

let tests : unit =
  let t = Sys.time() in
  for i = 0 to Array.length formulas -1 do
    let _ = satisfiable formulas.(i) in ()
  done;Printf.printf "Execution time (TABLEAU): %fs\n" (Sys.time() -. t);;